### ISSUE TITLE
import cycle not allowed for resolvers/referencers

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#1042]
### What happened?
since we have more and more resources in provider-aws we see go import cycle issues for resolvers/referencers:

- https://github.com/crossplane/provider-aws/pull/1041 (cannot set Resolvers/Referencers for LaunchTemplate & LaunchTemplateVersion in EC2-Instance)
- https://github.com/crossplane/provider-aws/pull/1022 (set Resolvers/Referencers for S3/Lambda)
- https://github.com/crossplane/provider-aws/pull/938
- https://github.com/crossplane/provider-aws/pull/830

<img width="601" alt="Bildschirmfoto 2021-12-31 um 10 44 45" src="https://user-images.githubusercontent.com/21083497/147819513-d1bbfb4e-a4d3-499e-beae-899c208b78bf.png">

### What environment did it happen in?
Crossplane version:

**Comment by muvaf** [comment]
One way could be to use `unstructured.Unstructured` in your own custom resolver. Though it'd be nice if we have that in crossplane-runtime similar to the existing strong-typed resolver.

**Comment by haarchri** [comment]
@muvaf  can you provide one example ?

**Comment by muvaf** [comment]
@haarchri I don't have a concrete example right now. Opened https://github.com/crossplane/crossplane-runtime/issues/313 with a bit more details.

**Comment by josegonzalez** [comment]
It would be great to re-open this. Currently there isn't a way to create/update a Launch Template and reference it when creating an ASG, meaning there is extra manual work if your Launch Template ever changes version (which is kinda the whole point of the thing).
