### ISSUE TITLE
Harden the provider-aws-controller docker image

### ISSUE THREAD

**Issue by HenriWilliams** [crossplane-contrib/provider-aws#1069]
### What problem are you facing?
It's currently possible to exec into the provider-aws-controller container and assume the IAM role of the container. Given that this container is often tied to an incredibly privileged IAM role it makes sense to reduce the attack surface as much as possible as a security measure.
The provider-aws-controller docker container is currently based on alpine which comes with a number of unnecessary binaries which are not required for the running of this service (sh,  busybox, etc.). Basing this container on a scratch container would reduce this attack surface and should make it a lot harder for someone to assume this privileged role by removing the possibility of starting a shell on this container.

### How could Crossplane help solve your problem?
Changing the provider-aws-controller [Dockerfile](https://github.com/crossplane/provider-aws/blob/master/cluster/images/provider-aws-controller/Dockerfile) to something similar to the code below could resolve this issue by utilising a multi-stage build to base the container on a scratch container.
``` dockerfile
FROM BASEIMAGE
RUN apk --no-cache add ca-certificates

FROM scratch

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ADD provider /usr/local/bin/crossplane-aws-provider

EXPOSE 8080
USER 1001
ENTRYPOINT ["crossplane-aws-provider"]
```

**Comment by hasheddan** [comment]
@HenriWilliams thanks for opening this! I am definitely in support of this change -- we have had an intention of switching over to distroless as we have with core Crossplane, and this work could likely be coupled with with a [switch to using `imagelight.mk`](https://github.com/crossplane/crossplane/pull/2718).

**Comment by haarchri** [comment]
we switched to distroless - so i will close this issue
