### ISSUE TITLE
change in  releaseVersion for nodegroup doesnt trigger reconcile

### ISSUE THREAD

**Issue by mqxter** [crossplane-contrib/provider-aws#1073]
### What happened?
nodegroup resource is not being updated after i change the  releaseVersion field. 
expected behavior: change in field should trigger a nodegroup update

### How can we reproduce it?
create an eks cluster version 1.20 and a node group. 
update the eks ckuster version via crossplane (works)
update the  releaseVersion and nothing happens 

### What environment did it happen in?
Crossplane version: 

 crossplane version 1.6.1
 aws provider crossplane/provider-aws:v0.23.0
 helm provider crossplane/provider-helm:v0.9.0

**Comment by cdenneen** [comment]
Since the atProvider doesn't currently return the `version` for `cluster` or `nodegroup` is it possible to be causing some of this?

**Comment by cdenneen** [comment]
@mqxter so `releaseVersion` isn't the correct `forProvider` parameter but `version`.
I tested and was able to upgrade the controlPlane and then nodeGroup using the version.
releaseVersion can be useful for patches but that is the ami version not the Kubernetes version.

So releaseVersion would be more like: `releaseVersion: 1.20.11-20220309`

If `version` works for you as well, then I think this can be resolved.
