### ISSUE TITLE
Restore RDS instance from a MySQL backup for DBInstance in RDS Group

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#1085]
### How could Crossplane help solve your problem?
implement Restore RDS instance from a MySQL backup for DBInstance in RDS Group as followup for https://github.com/crossplane/provider-aws/pull/770

**Comment by jbhennin** [comment]
@haarchri now that restoring from a snapshot has been implemented for RDS Instance would it make sense to go ahead and do this for DBInstance and DBCluster?

**Comment by haarchri** [comment]
@jbhennin didn you have time to Open a PR ? ;) I can review

**Comment by jbhennin** [comment]
Working on setting up time.  This should be an almost cut and paste.  Likely can get to it later this week or next.
