### ISSUE TITLE
Allow changing an RDS instance master password, e.g. after restoring from a snapshot

### ISSUE THREAD

**Issue by danports** [crossplane-contrib/provider-aws#1121]
This is a follow up from #1087.

### What problem are you facing?
As it stands, the provider will never set the master password for instances restored from snapshots: The underlying `RestoreDBInstanceFromDBSnapshot` AWS API call doesn't support it, and `GenerateModifyDBInstanceInput` disregards password changes. Thanks to the latter, there's also no way to change the master password for an existing RDS instance if the user desires that.

### How could Crossplane help solve your problem?
Provide some mechanism for changing RDS instance master passwords, e.g. by keeping them in sync with the referenced secret.

**Comment by eloo** [comment]
@danports 
i second that request because this would enable us to simply rebind a resource if the kubernetes resource of crossplane was remove with DeletionPolicy: orphan.

i have asked for this scenario in slack already:
https://crossplane.slack.com/archives/C01718T2476/p1643819387848399

**Comment by bianchi2** [comment]
I wonder if there's any workaround/hack other than calling AWS API directly to reset master credentials

**Comment by MisterMX** [comment]
Have you checked if #1756 made any differences?

**Comment by bianchi2** [comment]
On 0.42.0 it is still an issue.

**Comment by MisterMX** [comment]
As describe in https://github.com/crossplane-contrib/provider-aws/pull/1879#issuecomment-1754869940 I think the best way to solve this issue would be to implement something like #1756 for `RDSInstance` that stores the last password in a cache and performs and update if old and new passwords do not match.

**Comment by Yc-Chen** [comment]
I also suffer from the same issue
