### ISSUE TITLE
E2E tests should include a more comprehensive readiness check

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#1146]
### What problem are you facing?

Today e2e test includes waiting for `Provider` object to [report healthy](https://github.com/crossplane/provider-aws/blob/2ca12a6/cluster/local/integration_tests.sh#L173). However, in a [recent case](https://github.com/crossplane/provider-aws/pull/1145), we saw that the provider pod crashed after a few seconds since some of the fields were not registered in the schema.

### How could Crossplane help solve your problem?

We can either change package manager to report ready and healthy only after all controllers are up and starts to reconcile or maybe wait for a given time before calling `kubectl wait` command though that'd be a hack since it could take a while depending on the number of CRDs. cc @hasheddan

**Comment by haarchri** [comment]
what about a very simple kuttl test with our example directory ? we running this internally also for our providers

**Comment by muvaf** [comment]
I think that's an option but a bit hard to get right since the job can be interrupted at any time, hence we may leak resources in AWS.

**Comment by haarchri** [comment]
We don't need to create the resources in AWS - we can simply check created resources from examples without to check status - but we see If provider-aws creates the resources in k8s If you want i can open a PR
