### ISSUE TITLE
EventBridge/Cloudwatch Event Rules for a cron schedule to trigger an SNS topic

### ISSUE THREAD

**Issue by mikebollandajw** [crossplane-contrib/provider-aws#1150]
### What resource do you need?
EventBridge/Cloudwatch Event Rules for a cron schedule to trigger an SNS topic

### What is your use case?
We are using azure functions in kubernetes pods that are subscribed to SQS queues

In one scenario we wanted an azure function to trigger based on a cron schedule

Our crossplane charts create the azure function, sqs queue and sns event but we are missing the final piece for cron specific jobs

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?

Possibly

**Comment by mikebollandajw** [comment]
Is this something already in existence or part of #149

**Comment by sanketgawade** [comment]
We were looking for EventBridge functionality +1
