### ISSUE TITLE
OpenSearch support

### ISSUE THREAD

**Issue by goober** [crossplane-contrib/provider-aws#1167]
### What resource do you need?

I would like to be able to manage OpenSearch resources through Crossplane.

When https://github.com/crossplane/provider-aws/pull/1122 has been merged the code-generation can be used to ease the implementation.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
I can be assigned to this ticket and take a shot at it

**Comment by haarchri** [comment]
Closed for https://github.com/crossplane-contrib/provider-aws/issues/1228
