### ISSUE TITLE
Adding EncryptionConfiguration to ECR repos

### ISSUE THREAD

**Issue by dthomson25** [crossplane-contrib/provider-aws#1183]
### What resource do you need?
As a service, ECR support encrypting the repo with either AES256 or KMS (listed in [the docs here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/encryption-at-rest.html)). While Crossplane already supports creating ECR repos, it doesn't have the configuration options to add encryption to the ECRs repos with the current [ECR Repository field](https://doc.crds.dev/github.com/crossplane/provider-aws/ecr.aws.crossplane.io/Repository/v1beta1@v0.24.1). As a result, the default AES256 encryption is used, and users cannot use KMS to encrypt their ECR repos.

### What is your use case?
My organization requires us to encrypt images that are stored on ECR with KMS.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
Probably, but I cannot commit to that work yet.

**Comment by dthomson25** [comment]
I noticed that the ECR resources isn't using the code generator (https://github.com/crossplane/provider-aws/tree/master/apis/ecr). Would migrating it to the code generator help solve this issue or would it be easier to go add the missing fields?

**Comment by haarchri** [comment]
Think it's easy after https://github.com/crossplane/provider-aws/pull/1181
