### ISSUE TITLE
ec2-launchtemplate: SecurityGroup and Subnet Refs did not generate

### ISSUE THREAD

**Issue by BronzeDeer** [crossplane-contrib/provider-aws#1192]
### What happened?
Commit [713db3638](https://github.com/crossplane/provider-aws/commit/713db3638e67d569e215c8242d11838df1b1d3ee) introduced code generation annotations to generate Referencers for Subnet and SecurityGroup in launch template (analogous to the fields in ec2-instance). No such fields were generated and they are missing in the current CRDs. 

### How can we reproduce it?
The issue is present in the current CRDs generated by `make generate`

### What environment did it happen in?
provider-aws version: 
- 0.24.1
- master (8ab5582a as of writing)
- Likely present since introduction in 0.23.0

**Comment by haarchri** [comment]
in commit [713db3638](https://github.com/crossplane/provider-aws/commit/713db3638e67d569e215c8242d11838df1b1d3ee) we set subnet and security ref/selector for `ec2-instance` along with the launchtemplate pr 

for clarification you need an option to use ref/selector for:

https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/LaunchTemplate/v1alpha1@v0.24.1#spec-forProvider-launchTemplateData-securityGroupIDs 

https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/LaunchTemplate/v1alpha1@v0.24.1#spec-forProvider-launchTemplateData-networkInterfaces-subnetID

?

**Comment by BronzeDeer** [comment]
@haarchri  Thank you for the quick response, yes I was looking for the option to use ref/selector for the LaunchTemplate MR.
I guess misinterpreted the commit as also setting up the code generation for LaunchTemplate and not just ec2-instance
