### ISSUE TITLE
ec2-instance: imageId and launchtemplateId required even if launchtemplateName set

### ISSUE THREAD

**Issue by BronzeDeer** [crossplane-contrib/provider-aws#1193]
I am trying to spawn an Instance using a LaunchTemplate which has `imageId` set. I have set `launchTemplate.launchTemplateName` to reference said template. I expect that I only need to set `imageId` on the Instance CRD if I want to override the value  from the launchTemplate. Furthermore, based on the [documentation](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/Instance/v1alpha1@v0.24.1#spec-forProvider-launchTemplate), I expect that I must *not* also set `launchTemplate.launchTemplateId` since I have already set `launchTemplateName`

### What happened?

When trying to create the Instance Resource, I get two validation Errors, telling me that both `Instance.spec.forProvider.imageId` and `Instance.spec.forProvider.launchTemplate.launchTemplateId` are required fields

### How can we reproduce it?

The crd has the fields set as required ([here](https://github.com/crossplane/provider-aws/blob/4651608a57229248d92821af0eb03db9b80c7e6e/package/crds/ec2.aws.crossplane.io_instances.yaml#L500), and [here](https://github.com/crossplane/provider-aws/blob/4651608a57229248d92821af0eb03db9b80c7e6e/package/crds/ec2.aws.crossplane.io_instances.yaml#L948))

### What environment did it happen in?
Crossplane version: 
- aws-provider v0.24.1

**Comment by andrewli96** [comment]
I ran into this issue too. Here is the `workaround` I found and it works well for me:
1. Manually edit the instance CRD and remove `imageId` and `launchTemplateName`.  
```
$ kubectl edit crd instances.ec2.aws.crossplane.io
```

```diff 
...
 623                   launchTemplate:
 624                     description: The launch template to use to launch the instances.
 625                       Any parameters that you specify in RunInstances override the
 626                       same parameters in the launch template. You can specify either
 627                       the name or ID of a launch template, but not both.
 628                     properties:
 629                       launchTemplateId:
 630                         description: The ID of the launch template.
 631                         type: string
 632                       launchTemplateName:
 633                         description: The name of the launch template.
 634                         type: string
 635                       version:
 636                         description: "The version number of the launch template. \n
 637                           Default: The default version for the launch template."
 638                         type: string
 639                     required:
 640                     - launchTemplateId
-641                     - launchTemplateName
```

2. Re-apply the xr/xrc.

**Comment by DenisBaginsky** [comment]
This is still relevant and doesn't allow proper usage of Launch templates.
