### ISSUE TITLE
Minor: Misleading Deprecation Warning message on SNS group

### ISSUE THREAD

**Issue by luebken** [crossplane-contrib/provider-aws#1202]
### What happened?
I've just installed `provider-aws` on a fresh kind cluster: 
```
kubectl get providers
NAME                      INSTALLED   HEALTHY   PACKAGE                           AGE
crossplane-provider-aws   True        True      crossplane/provider-aws:v0.25.0   4m55s
```

When I query the managed resources, I get the following warning message: 
``` 
kubectl get managed
Warning: Please use v1beta1 version of SNS group.
No resources found
```
This is misleading in my point of view. I'm not using the deprecated v1alpha1 version of `SNSTopic.notification.aws.crossplane.io/v1alpha1`. The provider might have installed it but when I'm asking for all managed resources I'm not expecting deprecation warnings from resources I'm not using.

### What environment did it happen in?
Crossplane version: v1.6.4
Provider AWS: v0.25.0

**Comment by haarchri** [comment]
had a discussion after v0.24.x about this with @muvaf 
Output:
`Regarding the warning, I’m not sure if we can remove it. We’re using it just as upstream folks intended so it’s probably something to fix there, i.e. do not print deprecation notice if there is no resource on that version`

**Comment by jdfalk** [comment]
Is there a bug to follow up on this for changes upstream? Or is there any progress on this? We are managing multiple clusters and have hundreds of deprecation warnings for things that aren't being used.
