### ISSUE TITLE
Proposal: Add a LAST_SYNC printer column

### ISSUE THREAD

**Issue by MisterMX** [crossplane-contrib/provider-aws#1213]
### What problem are you facing?

When working with managed resources over time it becomes a problem to detect which resources have been touched lately by the controller. This is especially difficult if you have a lot of resources of the same type. For example in our environment we have over 200 `Secrets` alone.

Crossplane and its provider do write `LastTransitionTime` in the MR's `status.conditions` but the timestamp is in UTC which makes it hard to read if you don't happen to work in the UK.

### How could Crossplane help solve your problem?

A `LAST_SYNC` column should be added to every resource that shows the time since the last reconcile for `.status.conditions[?(@.type=='Synced')].lastTransitionTime` similar to the `AGE` column.

With kubebuilder this would be one additional line for every resource:

```go
// +kubebuilder:printcolumn:name="LAST_SYNC",type="date",JSONPath=".status.conditions[?(@.type=='Synced')].lastTransitionTime"
```

This might be a good enhancement for Crossplane and all other providers as well.

**Comment by haarchri** [comment]
good idea think we should do this in generated resources (but we need to open a PR in ack-code gen) and also for go-sdk v2 resources 

for code-gen check https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/crossplane/apis/crd.go.tpl#L66
