### ISSUE TITLE
Enable transferring ownership of OpenIDConnectProvider

### ISSUE THREAD

**Issue by ONordander** [crossplane-contrib/provider-aws#1280]
### What problem are you facing?

Currently it's not possible to transfer ownership of an `OpenIDConnectProvider` due to the fact that the external-name is configured by AWS.
### How could Crossplane help solve your problem?

Allowing the transfer would make it easier to bootstrap a Crossplane cluster without manual intervention to "clean up".
Here's an example of how it's done in the `Observe` stage with another resource that has an external-name managed by AWS https://github.com/crossplane/provider-aws/blob/master/pkg/controller/iam/policy/controller.go#L115 where the AWS resource is inferred by the name and path.

However in the case with `OpenIDConnectProvider` we cant infer which resource that maps to a Crossplane definiton since AWS doesn't use the name. My initial thought would be to tag the object during creation and when transferring the ownership use the tags to select the correct `OpenIDConnectProvider`.
If this approach sounds acceptable I could start working on a PR for this.

**Comment by xchan** [comment]
@ONordander There's an issue using iam role to service account at aws-cn region. Provider logs reveal that oidc provider is not found for current EKS. Is it related to the enhancement above?

**Comment by ONordander** [comment]
> @ONordander There's an issue using iam role to service account at aws-cn region. Provider logs reveal that oidc provider is not found for current EKS. Is it related to the enhancement above?

Not necessarily, atleast I have not seen that issue.
Did you create the `OpenIDConnectProvider` through Crossplane and did it succeed (the provider is not created by default)?

**Comment by xchan** [comment]
In my case, the OIDC provider is already created by Terraform together with EKS.

**Comment by ONordander** [comment]
> In my case, the OIDC provider is already created by Terraform together with EKS.

I see, if you think it's a bug I suggest you either open an issue here on Github with more information or use Crossplane's Slack.
If you provide an issue I can atleast take a look :)
