### ISSUE TITLE
Release v0.28.0 on June 01, 2022

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#1301]
### Checklist

* [x] Create the new release branch with minor version, i.e. `release-0.28` for `v0.28.0`.
  * You can use the existing branch for patch releases.
* [x] Tag release by running `Tag` action in Github UI against release branch, i.e. `release-X` branch.
  * Use v-prefixed version, like `v0.28.0`, for both description and tag.
* [x] Run `CI` action against release branch.
* [x] Tag the next pre-release by running `Tag` action in Github UI against `master` branch, if it's not a patch release.
  * The tag should be `v0.29.0-rc.0` if you're releasing `v0.28.x`.
* [x] Validate that you can install the published version, basic sanity check.
* [x] Run `Promote` action to promote it in `alpha` channel if it's pre-`1.0`.
* [x] Use Github UI to generate release notes.
  * Make sure to scan all PRs marked with `breaking-change` and add instructions for users to handle them.
* [x] Create the next release issue with a title that has its date, **4 weeks** after the current release day.
* [x] Announce in Slack, Twitter etc.

**Comment by muvaf** [comment]
I'll work on this today.

**Comment by haarchri** [comment]
@muvaf we have one Blocker with AssumeRole between 0.25 and master looks like go-sdk-v1 resources not working

**Comment by muvaf** [comment]
@haarchri Is there an issue describing the problem? Do you mean IRSA has not been working for sdk-v1 based resources for the couple last releases?

**Comment by haarchri** [comment]
Looks like we have the following issues:
https://github.com/crossplane-contrib/provider-aws/issues/1334 https://github.com/crossplane-contrib/provider-aws/issues/1289 https://github.com/crossplane-contrib/provider-aws/issues/1278

could be related to https://github.com/crossplane-contrib/provider-aws/pull/1240

**Comment by muvaf** [comment]
Opened https://github.com/crossplane-contrib/provider-aws/pull/1340 to unblock.

**Comment by muvaf** [comment]
@haarchri The PR is merged but I don't think I'll have time this week to complete the release with proper release notes. Do you mind taking over?

**Comment by haarchri** [comment]
i will start with release v0.26.2, v0.27.1 and v0.28.0

**Comment by haarchri** [comment]
basic check:

```
kubectl get pkgrev                   
NAME                                                           HEALTHY   REVISION   IMAGE                             STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-aws-600a696e071d   True      1          crossplane/provider-aws:v0.28.0   Active                               7m
```

```
kubectl get providers                
NAME           INSTALLED   HEALTHY   PACKAGE                           AGE
provider-aws   True        True      crossplane/provider-aws:v0.28.0   7m
```

```
 kubectl get pods -n crossplane-system
NAME                                         READY   STATUS    RESTARTS   AGE
crossplane-54f76b576b-zlh7z                  1/1     Running   0          21d
crossplane-rbac-manager-65c7c79c79-54gpj     1/1     Running   0         21d
provider-aws-600a696e071d-7b6c755496-9b9gd   1/1     Running   0          7m
```
