### ISSUE TITLE
Glue controllers lack features

### ISSUE THREAD

**Issue by MisterMX** [crossplane-contrib/provider-aws#1304]
### What happened?

Regarding v0.27.0, the current controllers for Glue are not fully implemented and lack a bunch of features, most notably lacking `lateInitialize` and `isUpToDate`. This applies to all currently existing Glue controllers: `classifier`, `connection`, `crawler`, `database`, `job`, `securityConfiguration`.

Additionally, a bunch of CRD fields are missing referencers.

### What environment did it happen in?
Provider version: v0.27.0

**Comment by haarchri** [comment]
think lateInitialize and isUpToDate are functions for beta quality - so happy to see a PR for these resources if you have time ;) i can review
