### ISSUE TITLE
Resource for Rules management and Alert Manager in Amazon Managed Prometheus (AMP)

### ISSUE THREAD

**Issue by Alex56p** [crossplane-contrib/provider-aws#1341]
### What resource do you need?
Add resource to manage Rules management and Alert manager in Amazon Managed Prometheus (AMP)

### What is your use case?
Be able to create update and delete Rules management and Alert Manager files in AMP

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?

Yes!

**Comment by haarchri** [comment]
You can Check: https://github.com/crossplane-contrib/provider-aws/blob/master/apis/prometheusservice/generator-config.yaml#L5

**Comment by r0mdau** [comment]
@haarchri a possible implementation for managing RuleGroupsNamespace in #1390 . I am working with @Edoz77 and @Alex56p .

Any comments are welcome in the PR, some paths are not crystal clear to me.

**Comment by r0mdau** [comment]
I will publish the AlertManagerDefinition CRD soon, work is almost done on my fork, it needs small polish.

**Comment by Alex56p** [comment]
@haarchri When can we expect to have a new release with this implementation in it?

**Comment by haarchri** [comment]
Will Cut the Release as soon as possible we are late - sorry for this
