### ISSUE TITLE
Logs: include field causing resource update

### ISSUE THREAD

**Issue by tbmetcalfe** [crossplane-contrib/provider-aws#1347]
Not sure if this belongs here or https://github.com/crossplane/crossplane.

### What problem are you facing?
When a resource has been deemed not up-to-date, you get an entry in the logs stream in the following format:

```
1.6547049284832287e+09	DEBUG	events	Normal	{"object": {"kind":"Distribution","name":"test-distribution","uid":"acf779fc-73ed-4ad5-bd1a-81eee8d0e4f9","apiVersion":"cloudfront.aws.crossplane.io/v1alpha1","resourceVersion":"589939344"}, "reason": "UpdatedExternalResource", "message": "Successfully requested update of external resource"}
```

It does not include which field does not match state of the resource.

### How could Crossplane help solve your problem?
Include which fields are causing a resource update in logs when the resource does not match.  It would be really useful to help debug when a resource is being updated when not expected. Perhaps the format: `Field in resource "spec.foo" does not match corresponding resource for x.aws.crossplane.io/v1alpha1, updating...` or something along those line.

**Comment by haarchri** [comment]
think @chlunde had the same idea in the past for rds - so a general approach would help - what do you think ?

**Comment by tbmetcalfe** [comment]
If that was aimed at me, I think a general approach would be the best. I don't know the code base, so I don't know how feasible that would be.
