### ISSUE TITLE
Support AWS RDS Serverless v2

### ISSUE THREAD

**Issue by cyboman32** [crossplane-contrib/provider-aws#1350]
### What problem are you facing?
We are using Crossplane to provision AWS resources of different kinds and RDS instances is one of them. We want to use RDS Serverless v2 which is available from may 2022 but seems this is not supported yet. Guess this requires to add ServerlessV2ScalingConfiguration part as provider configuration (https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html)

Would be nice to have such an ability or workaround. Thanks!

**Comment by janwillies** [comment]
we need to update the aws-go-sdk from [v1.42.0](https://github.com/crossplane-contrib/provider-aws/blob/master/go.mod#L6) to at least [v1.43.43](https://github.com/aws/aws-sdk-go/releases/tag/v1.43.43) first

**Comment by schroeder-paul** [comment]
A bump of the `aws-sdk-go` to the desired version results in errors while generation. See https://github.com/crossplane-contrib/provider-aws/issues/1414.

**Comment by MisterMX** [comment]
This seems to be implemented in https://github.com/crossplane-contrib/provider-aws/pull/1523. See also https://doc.crds.dev/github.com/crossplane/provider-aws/rds.aws.crossplane.io/DBCluster/v1alpha1@v0.33.0#spec-forProvider-scalingConfiguration for reference.

Feel free to reopen if something is missing.
