### ISSUE TITLE
cache v1beta1 ReplicationGroup: ReplicationGroupObservation diverges from AWS API

### ISSUE THREAD

**Issue by eaceaser** [crossplane-contrib/provider-aws#1358]
### What happened?
The ReplicationGroupObservation fields are highly divergent from the AWS API. Some examples:

* [NodeGroupID](https://github.com/crossplane/provider-aws/blob/51f6b67dedd84daca45bfac833f5a66c229e1eb2/apis/cache/v1beta1/replication_group_types.go#L87-L88) is called `port` for some reason
* [generateNodeGroup](https://github.com/crossplane-contrib/provider-aws/blob/51f6b67dedd84daca45bfac833f5a66c229e1eb2/pkg/clients/elasticache/elasticache.go#L446-L470) does not populate the [PrimaryEndpoint](https://github.com/crossplane/provider-aws/blob/51f6b67dedd84daca45bfac833f5a66c229e1eb2/apis/cache/v1beta1/replication_group_types.go#L95-L96) field, despite that being the field that is used as the actual [connection endpoint](https://github.com/crossplane-contrib/provider-aws/blob/51f6b67dedd84daca45bfac833f5a66c229e1eb2/pkg/clients/elasticache/elasticache.go#L517-L518)

At some point I'll try to PR some fixes for this, but I can't guarantee that I'm going to be able to fix all issues considering that this is all hand-written code interacting with the AWS API.

### How can we reproduce it?
Deploy a ReplicationGroup, look at status.atProvider.

### What environment did it happen in?
aws provider v0.28.0

**Comment by haarchri** [comment]
You can try generate the resource via code-gen https://github.com/crossplane-contrib/provider-aws/blob/master/apis/elasticache/generator-config.yaml#L13
