### ISSUE TITLE
Support for Cognito User-Pools User to Group membership relations

### ISSUE THREAD

**Issue by abacus3** [crossplane-contrib/provider-aws#1383]
### What resource do you need?

A Cognito User-Pool Group to User assignment is required. This is not mapped by the Amazon Cognito User-Pools API and therefore represents some sort of _virtual_ resource.

### What is your use case?

User-to-Group Memberships should be declaratively represented by a `CR` in order to manage User-to-Group assignments.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?

In case the code generator supports this: yes. Initial approach on utilizing the code generator failed due to insufficient features.

**Comment by haarchri** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_in_group

**Comment by abacus3** [comment]
@haarchri the implementation in https://github.com/crossplane-contrib/provider-aws/pull/1385 is analog to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_in_group and was built based on https://doc.crds.dev/github.com/crossplane/provider-aws/iam.aws.crossplane.io/GroupUserMembership/v1beta1@v0.29.0
