### ISSUE TITLE
[RDS DB Instance and maybe others] Tags do not update once set

### ISSUE THREAD

**Issue by tbmetcalfe** [crossplane-contrib/provider-aws#1436]
### What happened?

When you provision an RDS instance, and then attempt to update the tags, the tags will exist in the manage resource `forProvider`, but it will not actually update the tags in AWS. This does not cause the database to be updated in any way (i.e. it's not even attempting to update). 

If you look at the Cloudtrail API calls, you'll notice that tags are never included when updates are sent to AWS.

### How can we reproduce it?
1. Create an RDS instance with any tags you like. 
2. Update the list of tags
3. Note that the new tags never exist on the RDS instance in AWS.

### What environment did it happen in?
Crossplane version: 1.9.0
AWS Provider version: 0.29.0

* Cloud provider or hardware configuration: AWS EKS
* Kubernetes version (use `kubectl version`): v1.21.14-eks-18ef993
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS

**Comment by chlunde** [comment]
I think we should fix this after #1378 to avoid conflicts

**Comment by ricardomiguel-os** [comment]
There are other bugs reporting the same issue with tags update: [#1284](https://github.com/crossplane-contrib/provider-aws/issues/1284) [#1093](https://github.com/crossplane-contrib/provider-aws/issues/1093)

**Comment by SlevinWasAlreadyTaken** [comment]
@chlunde Hello :)
The PR https://github.com/crossplane-contrib/provider-aws/pull/1378 you mentioned stopped receiving updates then it froze this ticket and related ones.
Would you accept a fix for the update of tags aside it then?

**Comment by MisterMX** [comment]
Hey, there,
I currently don't have the time to work on #1378. I think it makes sense to foward with this issue instead.
