### ISSUE TITLE
List of strings order must match AWS list of strings order (possibly alphabetical) when reconciling 

### ISSUE THREAD

**Issue by tbmetcalfe** [crossplane-contrib/provider-aws#1437]
### What happened?

When trying to create an RDS instance in Crossplane, I noticed it was going through regular update cycles, meaning that the RDS instance was seldom in the available state. The reason for this ended up being that the list of strings in the `enableCloudwatchLogsExports` field were in a different order than what is reconciled against in the AWS list of strings.

### How can we reproduce it?

I suspect this will occur for many resources where an argument takes a list of strings. However for this particular case, create an RDS instance with this field set to:

```yaml
# this one caused RDS to go through regular update cycles
enableCloudwatchLogsExports:
              - upgrade
              - postgresql
``` 

You should notice that the RDS instance goes through regular update cycles.

Then set this field to:
```yaml
# this one works as expected
enableCloudwatchLogsExports:
              - postgresql
              - upgrade
```

And note that the update cycles stop.

### What environment did it happen in?
Crossplane version: 1.9.0
AWS Provider version: 0.29.0

Cloud provider or hardware configuration: AWS EKS
Kubernetes version (use kubectl version): v1.21.14-eks-18ef993
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS

**Comment by chlunde** [comment]
I should make a PR for this, https://github.com/sparebank1utvikling/provider-aws/commit/b2c3c7ccb46095e1bc2485fed681c3443082ab27

I wonder if we should remove CloudwatchLogsExportConfiguration at the same time
