### ISSUE TITLE
Meta: Request Reviews from maintainers

### ISSUE THREAD

**Issue by MisterMX** [crossplane-contrib/provider-aws#1444]
### Description of the issue

Regular contributors (like me) don't have the ability to use Github's "Request Review" feature to ask a maintainer to look at a PR. They always have to tag a specific person in the request, like @haarchri or @muvaf. This slows down the review process because the addressed person might be unavailable at that time. It is also difficult for new contributors because they most likely do not know the maintainers and which to address.

### How could this issue be solved

Add the ability to request a review from the `provider-aws-maintainers` team (or whatever you would like to call it) from the PR menu.

This might be interesting for other repos in `crossplane-contrib` as well although I am not sure if its a good idea to interfere with their development process from the outside.

**Comment by chlunde** [comment]
CODEOWNERS is also an option. For example we could be pinged any time someone makes a PR touching RDS, ElastiCache and SecurityGroups, and then maybe someone else could handle other controllers.

**Comment by haarchri** [comment]
@jbw976 fyi
