### ISSUE TITLE
AWS Opensearch implementation

### ISSUE THREAD

**Issue by mvkrishna86** [crossplane-contrib/provider-aws#1445]
### What resource do you need?
AWS Opensearch

### What is your use case?
We are using aws opensearch in our project, we are able to create all other components with crossplane except opensearch. 

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
I would like to try, but not sure if I can implement a production ready code.

**Comment by haarchri** [comment]
Please check https://github.com/crossplane-contrib/provider-aws/pull/1333
