### ISSUE TITLE
add @MisterMX as Maintainer provider-aws

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#1446]
@MisterMX  has been contributing significant features to provider-aws over the past few months. He has also been responsive and reactive to opened issues and big fixes. I believe he has demonstrated all qualities we expect in a Crossplane maintainer.

This issue proposes adding @MisterMX as a provider-aws maintainer. Existing maintainers should indicate votes in the comments.

/cc @muvaf @chlunde @jbw976

**Comment by chlunde** [comment]
+1

**Comment by MisterMX** [comment]
Thanks for pushing this @haarchri!

**Comment by janwillies** [comment]
+1 from me (NB)

**Comment by jbw976** [comment]
+1 NB from me - i'm in support of this as well as @MisterMX has been doing great work all around.

I've added this topic to the community meeting today to see if we can wrangle up a few more +1's from existing maintainers in this repo.

Then we'd want to open a PR to add max to the https://github.com/crossplane-contrib/provider-aws/blob/master/OWNERS.md file, and then add him to https://github.com/crossplane-contrib/provider-aws/settings/access.

@negz @hasheddan @muvaf @turkenh @ulucinar @AaronME - any support you'd like to add for this proposal? :)

**Comment by hasheddan** [comment]
+1 (binding)

**Comment by turkenh** [comment]
+1 (binding) 🙌

**Comment by muvaf** [comment]
+1 !!

**Comment by jbw976** [comment]
I count 5 maintainers that have given their support to this: @haarchri, @chlunde, @hasheddan, @turkenh, @muvaf 

That support seems totally reasonable to me to move forward - @haarchri feel free to open a PR that updates the OWNERS.md file and get that merged in.  Then ping me if you need help in adding maintainer permissions for @MisterMX 🙇

**Comment by haarchri** [comment]
added #1491 for OWNERS.md ;)

**Comment by jbw976** [comment]
I've sent @MisterMX an invitation to have "Maintain" permissions on this repository.  Thanks for all your contributions @MisterMX!! 💪 🙇

**Comment by MisterMX** [comment]
Thanks a lot for the great support! :)
