### ISSUE TITLE
allow creation of s3 buckets with no encryption

### ISSUE THREAD

**Issue by mqxter** [crossplane-contrib/provider-aws#1470]
### What happened?
need to create a non encrypted bucket to serve static assets via cloudfront.
cloudfront doesnt support encrypted buckets. 

creation of a new s3 bucket with empty 
serverSideEncryptionConfiguration.rules: []
results an error 
update failed: cannot create or update: api error MalformedXML: The
      XML you provided was not well-formed or did not validate against our published
      schema

### How can we reproduce it?
attaching a bucket manifest to reproduce

apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-test-aws-prodvider-s3
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    corsConfiguration:
      corsRules:
      - allowedHeaders:
        - Content-Length
        - Authorization
        allowedMethods:
        - GET
        allowedOrigins:
        - '*'
        maxAgeSeconds: 3000
    lifecycleConfiguration:
      rules:
      - noncurrentVersionExpiration:
          noncurrentDays: 180
        status: Enabled
    locationConstraint: us-east-1
    publicAccessBlockConfiguration:
      blockPublicAcls: false
      blockPublicPolicy: false
      ignorePublicAcls: true
      restrictPublicBuckets: false
    serverSideEncryptionConfiguration:
      rules: []
    tagging:
      tagSet:
      - key: usedBy
        value: crossplane
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: default

### What environment did it happen in?
aws provider 0.31.0

**Comment by patelronak** [comment]
@mqxter you request is valid but we do have default encryption enabled on our s3 buckets that are served through cloudfront using `Amazon S3-managed keys (SSE-S3)` for encryption key type.  You should be able to setup at rest encryption for your s3 bucket that is used by cloudfront.

**Comment by mqxter** [comment]
Will check that and update
