### ISSUE TITLE
Implement the EKS Update Resource for NodeGroups

### ISSUE THREAD

**Issue by baldorch** [crossplane-contrib/provider-aws#1475]
### What problem are you facing?
Currently I cannot see if a NodegroupUpdate failed and I have no knowledge about previous updates. If an update fails the resource updated goes back to its previous configuration and into the `Active` state. From the provider point of view nothing changed at AWS and it will try to reconcile the Nodegroup again, triggering a new update and most probably run into the same Problem.

### How could Crossplane help solve your problem?
I would like to add an Array of Updates to the `NodeGroupObservation`. Each of the Updates is supposed to be of type `eks.Update`. The `nodegroup.Controller` is responsible for writing the Updates to that array. Like this failing updates and their reason are visible to the user.

I am also open for other ideas on how to make these objects or this information available. If a full list is too long, maybe only the latest Update and it's state can be included in the Observation.

**Comment by haarchri** [comment]
implemented with #1469
