### ISSUE TITLE
Replace Web Identity Token logic on next release of aws-sdk-go-v2

### ISSUE THREAD

**Issue by hasheddan** [crossplane-contrib/provider-aws#148]
### What problem are you facing?

We currently assume IAM roles for authentication to the AWS API using our own custom logic to get Web Identity Tokens from the file-system of the controller container. The v1 version of `aws-sdk-go` supported this use-case as an identity provider, but the v2 version did not, so we were forced to use our own implementation in the short-term.

### How could Crossplane help solve your problem?

This logic has now been included in `aws-sdk-go-v2` as part of https://github.com/aws/aws-sdk-go-v2/pull/488. It should be available in the next release (`v0.20.0`), and we should move to using it instead of our own implementation.

**Comment by hasheddan** [comment]
As of [v0.20.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.20.0), the Web Identity Credential Provider has been added. We should bump our dependency on the AWS SDK and use this functionality instead of our own implementation: https://github.com/crossplane/provider-aws/blob/62cca4c8941462a65d6499d6bba43b7cd84cdc38/pkg/clients/aws.go#L108

**Comment by haarchri** [comment]
@hasheddan is this still relevant ?
