### ISSUE TITLE
Support for disktype for nodegroup

### ISSUE THREAD

**Issue by mohanakumar** [crossplane-contrib/provider-aws#1492]
While creating nodegroup we have the option to specify disksize. We also need the option to specify disktype (gp2, gp3 etc..)

https://doc.crds.dev/github.com/crossplane/provider-aws/eks.aws.crossplane.io/NodeGroup/v1alpha1@v0.30.0

**Comment by zetamorph** [comment]
I think you need to go with a custom launch template to configure the disk type, it's the same situation with the AWS CLI: [create-nodegroup](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/create-nodegroup.html) only allows configuring the disk size.

To configure the disk type, you need to [create a launch template](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-launch-template.html) and attach it to the nodegroup.

**Comment by haarchri** [comment]
@zetamorph is correct - you need to use custom Launch Template
