### ISSUE TITLE
Consider adding vpcPeeringConnectionIdRef in Route table

### ISSUE THREAD

**Issue by Rishikeshcg** [crossplane-contrib/provider-aws#1497]
In the route tables, there is no option to refer a peering connection without hardcoding the peering connection id. If vpcPeeringConnectionIdRef or Selector is added, there is no need to hardcode the peering id.

**Comment by haarchri** [comment]
please ouse RouteTable in combination with Route Resource https://github.com/crossplane-contrib/provider-aws/blob/master/apis/ec2/v1alpha1/custom_types.go#L277 in Route Resource we have the Option for `VPCPeeringConnectionIDRef`
