### ISSUE TITLE
Release v0.33.0 on Oct 10, 2022 release, remove notification APIGroup (old release date Oct 19, 2022)

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#1502]
### Checklist

**we will remove deprecated  APIGroups**:

- notification APIGroup with Release v0.33.0 at Oct. 19, 2022 - please migrate to sns APIGroup check for reference: https://github.com/crossplane-contrib/provider-aws/issues/1202, https://github.com/crossplane-contrib/provider-aws/pull/1123, https://github.com/crossplane-contrib/provider-aws/pull/1487

- provider APIGroup with Release (deprecated provider (https://doc.crds.dev/github.com/crossplane-contrib/provider-aws/aws.crossplane.io/Provider/v1alpha3@v0.32.0) APIGroup - please migration to providerConfig APIGroup) v0.33.0 at Oct. 19, 2022 - please migrate to providerConfig APIGroup 
* [x] Create the new release branch with minor version, i.e. `release-0.21` for `v0.21.0`.
  * You can use the existing branch for patch releases.
* [x] Tag release by running `Tag` action in Github UI against release branch, i.e. `release-X` branch.
  * Use v-prefixed version, like `v0.21.0`, for both description and tag.
* [x] Run `CI` action against release branch.
* [x] Tag the next pre-release by running `Tag` action in Github UI against `master` branch, if it's not a patch release.
  * The tag should be `v0.22.0-rc.0` if you're releasing `v0.21.x`.
* [x] Validate that you can install the published version, basic sanity check.
* [x] Run `Promote` action to promote it in `alpha` channel if it's pre-`1.0`.
* [x] Use Github UI to generate release notes.
  * Make sure to scan all PRs marked with `breaking-change` and add instructions for users to handle them.
* [x] Create the next release issue with a title that has its date, **4 weeks** after the current release day.
* [x] Announce in Slack, Twitter etc.

**Comment by hasheddan** [comment]
@haarchri it looks like issues linked have been addressed -- could we release sooner than October 19th here?

**Comment by haarchri** [comment]
We can if no one has something more for the Release

**Comment by haarchri** [comment]
```
NAME                                                           HEALTHY   REVISION   IMAGE                                              STATE      DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-aws-245ce7fb587d   True      2          docker.io/crossplane/provider-aws:v0.32.0          Inactive                               10d
providerrevision.pkg.crossplane.io/provider-aws-e0b33d016bb8   True      3          docker.io/crossplanecontrib/provider-aws:v0.33.0   Active                                 24m
```

```
 kubectl get pods -n crossplane-system
NAME                                         READY   STATUS    RESTARTS   AGE
crossplane-7958b864ff-qfdnc                  1/1     Running   0          17d
crossplane-rbac-manager-567778c659-lk4mn     1/1     Running   0          17d
provider-aws-e0b33d016bb8-5d7595b8cd-jbs6k   1/1     Running   0          23m
```
