### ISSUE TITLE
promote ci-action is not working since go1.18

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#1503]
### What happened?
promote ci-action is failing since go1.18
https://github.com/crossplane-contrib/provider-aws/actions/runs/3158300558/jobs/5140292589

```
Run make -j2 promote BRANCH_NAME=${GITHUB_REF##*/}
build/makelib/golang.mk:93: *** "go version 1.17 is not supported. required version is 1.18".  Stop.
Error: Process completed with exit code 2.
```

### What environment did it happen in?
Crossplane version:

**Comment by haarchri** [comment]
@chlunde @hasheddan  any ideas ?

**Comment by hasheddan** [comment]
I can take this one 👍🏻
