### ISSUE TITLE
Update rds/v1alpha1.DBCluster/DBInstance to have restoreFrom feature parity with database/v1beta1.RDSInstance 

### ISSUE THREAD

**Issue by pjferrell** [crossplane-contrib/provider-aws#1512]
### What problem are you facing?
rds/v1alpha1 and database/v1beta1 leverage the same client, but do not have feature parity for restoring data from backups (snapshot/pointintime/s3).  The purpose of this feature request would be to add support to DBCluster/DBInstance resources to match the supported functionality in RDSInstance (and backend aws client).

Provisioning Aurora DBs requires the use of rds/v1alpha1.DBCluster and DBInstance resources.  Support for s3 restoreFrom was added to DBCluster through PR in Aug 2022 ([PR-1428])(https://github.com/crossplane-contrib/provider-aws/pull/1428).  

### How could Crossplane help solve your problem?
It seems there is functional overlap in RDSInstance and DBInstance.  Both allow the provisioning of db hosts, but DBCluster/DBInstance allows the additional provisioning of Aurora instances.  What is the roadmap/direction that provider-aws has planned for these two API groups (database vs rds).  Are there plans to deprecate database/RDSInstance in favor of rds/DBInstance in the future?

I'll be starting work on a candidate PR that follows the existing restoreFrom implementations in RDSInstance and DBCluster.  Review / guidance on the direction that Crossplane has for the two API groups would help to avoid work that will not be accepted to the code base.

**Comment by MisterMX** [comment]
Relevant for #1559
