### ISSUE TITLE
Routes are getting removed

### ISSUE THREAD

**Issue by Rishikeshcg** [crossplane-contrib/provider-aws#1518]
Hi,
I have a requirement to use vpc peering connection reference in the route table entry rather than hardcoding the vpc peering connection id. I am using a combination of Route table and Route resource but the routes added using Route resource are getting removed from the Route table. Only the entries added in the Route table (routes in the spec) resource persists.

**Comment by haarchri** [comment]
You need to add https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/RouteTable/v1beta1@v0.28.1#spec-forProvider-ignoreRoutes
