### ISSUE TITLE
Broken Link to Documentation in Readme

### ISSUE THREAD

**Issue by tillepille** [crossplane-contrib/provider-aws#1524]
### What happened?

The link on <https://github.com/crossplane-contrib/provider-aws/blob/master/README.md?plain=1#L21>

ends in a 404

### How can we reproduce it?

try open https://crossplane.io/docs/latest

### What environment did it happen in?
Crossplane version: master

### Possible Solution

There is either <https://crossplane.io/docs/master>
Or a link to a fixed release like <https://crossplane.io/docs/v1.9>

**Comment by haarchri** [comment]
fixed with #1526
