### ISSUE TITLE
Add support for RDS option group

### ISSUE THREAD

**Issue by dudicoco** [crossplane-contrib/provider-aws#1530]
### What resource do you need?

[RDS option group](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithOptionGroups.html)

### What is your use case?

It's a basic feature of RDS which I was surprised to find out isn't supported yet by the provider.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
Yes.

**Comment by haarchri** [comment]
Is possible via Code-Generator https://github.com/crossplane-contrib/provider-aws/blob/master/apis/rds/generator-config.yaml#L69 you can try it out ;)
