### ISSUE TITLE
Error while installing  crossplane/provider-aws:v0.33.0

### ISSUE THREAD

**Issue by Gobi-Ganesan** [crossplane-contrib/provider-aws#1584]
### What happened?
Can’t able to install crossplane/provider-aws:v0.33.0.
Facing the below error
```
Events:
  Type     Reason         Age                From                                 Message
  ----     ------         ----               ----                                 -------
  Warning  UnpackPackage  0s (x26 over 20m)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: HEAD https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.33.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details): GET https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.33.0: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v0.33.0

```
### How can we reproduce it?
 kubectl crossplane install provider crossplane/provider-aws:v0.33.0

### What environment did it happen in?
Crossplane version: crossplane-1.10.1

**Comment by Gobi-Ganesan** [comment]
@haarchri Do you mean from v0.33.0 provider-aws moved from **crossplane/provider-aws** to **crossplanecontrib/provider-aws**?

**Comment by haarchri** [comment]
Yes

**Comment by Gobi-Ganesan** [comment]
Thanks, @haarchri.  Is somewhere this Information documented?

**Comment by haarchri** [comment]
First entry in Release Notes https://github.com/crossplane-contrib/provider-aws/releases/tag/v0.33.0

**Comment by Gobi-Ganesan** [comment]
My bad. Thanks for the information. I'll close this issue.
