### ISSUE TITLE
RouteTable routes are deleting

### ISSUE THREAD

**Issue by ym-Arcadia** [crossplane-contrib/provider-aws#1593]
Hi

I am using a combination of the `RouteTable` and `Route` resources but the route added using the `Route` resource are getting deleted by the `RouteTable` resource. Only the routes added in the `RouteTable` resource persist. I added [ignoreRoutes](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/RouteTable/v1beta1@v0.34.0#spec-forProvider-ignoreRoutes) as well in `RouteTable` resource. 

RouteTable Resource
![RouteTable](https://user-images.githubusercontent.com/103582148/206093988-c8499e01-6315-4b23-872c-2c76e3aa2315.JPG)

Route Resource
![Route](https://user-images.githubusercontent.com/103582148/206094280-29e0245f-c5cb-4c57-a5d8-febba92aa68a.JPG)

**Comment by ym-Arcadia** [comment]
Routes added
![1](https://user-images.githubusercontent.com/103582148/206095165-e709e8c9-9986-42b5-9e0b-32e17ce1d5a1.JPG)

Routes deleted
![2](https://user-images.githubusercontent.com/103582148/206095195-98857db7-f2de-4e04-97f0-4a27d9699ba1.JPG)

**Comment by haarchri** [comment]
Can you remove complete Routes in RouteTable and use only Route resource ? Does this make a difference ?

**Comment by ym-Arcadia** [comment]
@haarchri It works, thank you for the quick response.
