### ISSUE TITLE
NodeGroup - releaseVersion not updated to correspond version after upgrade

### ISSUE THREAD

**Issue by bzurek1** [crossplane-contrib/provider-aws#1601]
**What happened?**
After upgrading my EKS Clusters and NodeGroups from version 1.22 to 1.23 (and then same for 1.24), I observed the following error message.

`cannot update EKS node group version: InvalidParameterException: Requested release version 1.22.6-20220526 is not valid for kubernetes version 1.24.`

The error goes away and correct value for `releaseVersion` is set once it gets manually set to null in NodeGroup manifest.

Looks like `spec.forProvider.releaseVersion` doesn't get automatically updated to correspond `spec.forProvider.version` when it has got a non-null value.

**How can we reproduce it?**

- Create a Cluster + NodeGroup with `version` set to 1.22
- Change `version` to 1.23 on both and wait for upgrade
(optionally - to see the exact error message I pasted earlier - upgrade to 1.24 afterwards)

**What environment did it happen in?**

Crossplane version: 1.9.1
AWS provider version: v0.34

**Comment by adrienzieba** [comment]
Hello,

I encountered the same issue. For now, as a workaround, I'm patching the resource with the information in the status.

```
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.releaseVersion
          toFieldPath: status.cluster.releaseVersion

        - fromFieldPath: status.cluster.releaseVersion
          toFieldPath: spec.forProvider.releaseVersion
          type: FromCompositeFieldPath
```
