### ISSUE TITLE
Cloudfront distribution does not get deleted 

### ISSUE THREAD

**Issue by fabioaraujopt** [crossplane-contrib/provider-aws#1622]
### What happened?
A cloudfront distribution does not get deleted by crossplane. The deletion of a cloudfront distribution is done in 2 steps check [Deleting a distribution](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HowToDeleteDistribution.html), first by disable the distribution then by requesting its deletion.

### How can we reproduce it?
Create a cloudfront distribution using the following CRD https://doc.crds.dev/github.com/crossplane/provider-aws/cloudfront.aws.crossplane.io/Distribution/v1alpha1@v0.35.0.

Try to delete the resource by deleting the CRD from the cluster. 

Check the provider-aws logs warning message:

`Warning: "reason": "CannotDeleteExternalResource", "message": "pre-delete failed: distribution needs to be disabled before deletion"`

### What environment did it happen in?
Crossplane version:  1.9.1
provider-aws version: v0.32.0-rc.0.18.gc8c29463

**Comment by haarchri** [comment]
You need to set first enabled to false https://doc.crds.dev/github.com/crossplane/provider-aws/cloudfront.aws.crossplane.io/Distribution/v1alpha1@v0.35.0#spec-forProvider-distributionConfig-enabled then it's possible

**Comment by fabioaraujopt** [comment]
Shouldn't this be part of the provider?

**Comment by haarchri** [comment]
No because its a flag in the api
