### ISSUE TITLE
Vulnerabilites in aws provider 0.35.0

### ISSUE THREAD

**Issue by dacoty** [crossplane-contrib/provider-aws#1628]
When running the provider in my local kube cluster ( docker-desktop) the image has some vulnerabilities, which should be patched up if possible for the next release. 
screenshot below shows the affected packages and CVE numbers. 
![image](https://user-images.githubusercontent.com/121582995/212126648-b0656cf3-2f1b-4c27-a25b-fb1a32bc4cb0.png)

Sorry for opening a general issue, i wasn't sure if this falls in any other listed category.

**Comment by haarchri** [comment]
are you willing to contribute ? =)

**Comment by dacoty** [comment]
@haarchri sure, I can try to make a PR for this over the holiday weekend
