### ISSUE TITLE
Elasticache ReplicationGroup deletes the secret (writeConnectionSecretToRef) even when deletionPolicy is set to Orphan 

### ISSUE THREAD

**Issue by orkramer** [crossplane-contrib/provider-aws#1634]
### What happened?
Elasticache ReplicationGroup deletes the secret (writeConnectionSecretToRef) even when deletionPolicy is set to Orphan 

### How can we reproduce it?
1. Create Replication group with deletionPolicy: 'Orphan'
2. Delete the object in k8s
3. Aws redis was not deleted indeed 
4.  writeConnectionSecretToRef was deleted from k8s
**5. when the k8s object was restored , the secret was recreated but without the password key in secret**

### What environment did it happen in?
Crossplane version: 
'crossplane/crossplane:v1.10.1'

AWS EKS 1.21

**Comment by haarchri** [comment]
Orphan means that the resource is deleted in k8s cluster - but not in aws
