### ISSUE TITLE
spec.forProvider.masterUserPasswordSecretRef shouldn't be required when creating a secondary Aurora cluster

### ISSUE THREAD

**Issue by javierlopez-itech** [crossplane-contrib/provider-aws#1668]
I am trying to create a Global Aurora Cluster on AWS, the setup should look like this:

GlobalCluster
  - Regional Cluster 1 (Primary)
  - - Instance 1a
  - - Instance 1b
  - Regional Cluster 2 (Secondary)
  - - Instance 2a
  - - Instance 2b
 
The problem is that, when creating a new cluster `spec.forProvider.masterUserPasswordSecretRef` is mandatory for all clusters, no matter whether they are the primary or secondary cluster. It makes sense, that for the primary cluster this value is mandatory, but not for the second one. Right now I have the following problem:

1. If I don't specify a value for `spec.forProvider.masterUserPasswordSecretRef` in the secondary cluster, Crossplane won't let me create it.

2. If I do specify a value for `spec.forProvider.masterUserPasswordSecretRef`, Crossplane will let me create the CRD but AWS API will complain with the following error message:
```
create failed: cannot create DBCluster in AWS: InvalidParameterCombination: Cannot specify password for cross region replication cluster
```

So I'm afraid there is no way around that other than making `masterUserPasswordSecretRef` not mandatory but specify in the documentation that is actually mandatory if you only have one.

**Comment by nashtapu-tibco** [comment]
@javierlopez-itech / @MisterMX which version is this fixed in?
I still see the issue in provider-aws:v0.43.1
```
      message: 'create failed: pre-create failed: neither a masterUserPasswordSecretRef
        is given, nor password autogeneration was enabled, not a restore is performed'
      reason: ReconcileError
```
