### ISSUE TITLE
Kafka is editing it's own spec

### ISSUE THREAD

**Issue by drewwells** [crossplane-contrib/provider-aws#1673]
I noticed an odd entry in my spec which prevented MSK cluster from provisioning.

```
      configurationInfo:
        arn: arn:aws:kafka:us-east-1:575487752567:configuration/resource-controlplane/aef15868-2f1e-438f-a5fc-a7edaad68bb7-20
        arnRef:
          name: resource-controlplane
```

It appears the controller is modifying its own spec, which caused an issue here. Especially because it often leads to an issue where an invalid arn is entered in this spec that breaks kafka cluster creation. I found this entry on a cluster that was reinstalled:

```
      configurationInfo:
        arn: resource-controlplane
        arnRef:
          name: resource-controlplane
```

repo steps:
1. stand up provider-aws and provision CRs
```
kubectl apply -f examples/kafka/cluster.yaml -f examples/kafka/configuration.yaml
```
2. Inspect configurationInfo, see that arn was updated to an invalid value and cluster fails to provision
```
 k get cluster.kafka example -o yaml | grep '^    configurationInfo' -A4
    configurationInfo:
      arn: example-configuration
      arnRef:
        name: example-configuration
      revision: 1
```
3. Events show errors resolving this string since it's not an arn
```
  Warning  CannotResolveResourceReferences  6s               managed/cluster.kafka.aws.crossplane.io  cannot resolve references: mg.Spec.ForProvider.CustomClusterParameters.CustomConfigurationInfo.ARN: cannot get referenced resource: Configuration.kafka.aws.crossplane.io "example-configuration" not found
  Warning  CannotResolveResourceReferences  6s               managed/cluster.kafka.aws.crossplane.io  cannot resolve references: mg.Spec.ForProvider.CustomClusterParameters.CustomConfigurationInfo.ARN: referenced field was empty (referenced resource may not yet be ready)
  Warning  CannotCreateExternalResource     5s (x5 over 6s)  managed/cluster.kafka.aws.crossplane.io  cannot create Cluster in AWS: UnrecognizedClientException:
           status code: 403, request id:
 ```

**Comment by drewwells** [comment]
I thought a bit about what's happening here. I believe this problem occurs because cluster controller is unable to find the configuration aws resource, since it does not yet exist in aws. As a result, it's falling back to a default external name instead of waiting to find the arn name. Removing this default behavior should trigger the right series of steps.

**Comment by drewwells** [comment]
imo, the configuration ARN should be set in the status or only be looked up directly from the config CR

**Comment by MisterMX** [comment]
The issue still persists. A custom resolver function is necessary that extracts the ARN instead of defaulting to the external name.
