### ISSUE TITLE
Add ElastiCache support

### ISSUE THREAD

**Issue by infinitecompute** [crossplane-contrib/provider-aws#168]
### What problem are you facing?
Would like add support for ElastiCache resource

### How could Crossplane help solve your problem?
Enables creation of ElastiCache resources

### References
* https://crossplane.io/docs/v0.9/api/crossplane/provider-aws/cache-aws-crossplane-io-v1beta1.html

**Comment by negz** [comment]
We already have support for AWS ElastiCache ReplicationGroups. I don't think adding cache cluster support would add much value; I believe you can do everything you can do with a cache cluster using a replication group. We'll still want cache clusters eventually, but it's not a high priority.

**Comment by haarchri** [comment]
CacheCluster is implemented https://doc.crds.dev/github.com/crossplane/provider-aws/cache.aws.crossplane.io/CacheCluster/v1alpha1@v0.28.1 also a lot of other resources in Cache Group
