### ISSUE TITLE
unable to use crossplane with localstack 

### ISSUE THREAD

**Issue by Shubhambawa98** [crossplane-contrib/provider-aws#1680]
apiVersion: aws.upbound.io/v1beta1

kind: ProviderConfig

metadata:

  name: default

spec:

  endpoint:

    hostnameImmutable: true

    url:

      type: Static

      static: http://172.32.15.81:31566

  credentials:

    source: Secret

    secretRef:

      namespace: crossplane-system

      name: aws-secret

      key: creds

Warning  CannotConnectToProvider          2m26s (x15 over 2m38s)  managed/s3.aws.upbound.io/v1beta1, kind=bucket  (combined from similar events): cannot get terraform setup: cannot get the caller identity: GetCallerIdentity query failed: GetCallerIdentity query failed: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: f0849dda-504f-4f42-999b-ab7aab249dde, api error InvalidClientTokenId: The security token included in the request is invalid.

### What environment did it happen in?
Crossplane version:

**Comment by haarchri** [comment]
please open an issue in upbound/provider-aws checkout https://github.com/upbound/provider-aws/pull/447 because this here is community-provider-aws and localstack is working with https://github.com/haarchri/provider-aws-issue-1017/blob/main/providerconfig.yaml
