### ISSUE TITLE
Updating DBClusterParameterGroup on a RDS DBCluster

### ISSUE THREAD

**Issue by maxforasteiro** [crossplane-contrib/provider-aws#1688]
### What happened?

Hey!

So, I was trying to implement a new DB Cluster Parameter Group for my already existing DB Clusters and even tho I could validate that the Parameter Groups were created correctly, while trying to link them with the Clusters, it seems not to be syncing.
While describing my `rds.aws.crossplane.io/v1alpha1/dbclusters` I can see that the `forProvider` part is correct, pointing to the correct `dbClusterParameterGroupName`, but the `status.atProvider` shows me the `dbClusterParameterGroup` with the old value and `dbClusterMembers[0].dbClusterParameterGroupStatus` with `in-sync` (as per image bellow)
![Screenshot 2023-03-02 at 08 51 51](https://user-images.githubusercontent.com/18661016/222365267-3fef5ba1-fd19-4242-b863-69c55643f378.png)

I couldn't wrap my head around the implementation to try to understand why and the logs were also not helpful in this case, since everything seems to be in-sync.

### How can we reproduce it?

We already had a CRD for our DB Clusters, creating the cluster, the instance and the Security group. While extending the behavior of this CRD to include DB Cluster parameter groups, we noticed that **existing DB Clusters** were not being updated with the new db cluster parameter group. 
Note that for **new DB Clusters** it works, they are created with the correct db cluster parameter group.

### What environment did it happen in?
* Crossplane version: v1.9.0
* Cloud provider: AWS
* Kubernetes version: 1.23
* Provider AWS version: 0.31.0

**Comment by MisterMX** [comment]
Can you provide a full example to reproduce this issue?

Note that if you haven't set `applyImmediately: true`, the changes are only applied during the next maintenance window.

**Comment by maxforasteiro** [comment]
> Can you provide a full example to reproduce this issue?
> 
> Note that if you haven't set `applyImmediately: true`, the changes are only applied during the next maintenance window.

[The docs](https://doc.crds.dev/github.com/crossplane/provider-aws/rds.aws.crossplane.io/DBCluster/v1alpha1@v0.31.0#spec-forProvider-applyImmediately) does not mention changes on the DB Cluster parameter group. Still, I would imagine that at least the `dbClusterMembers[0].dbClusterParameterGroupStatus` would change to `pending-reboot` or something like this. I validate that if I manually perform the changes on AWS Console it shows as pending-reboot, which makes me think that the problem is that crossplane is not even asking for the change in the first place.

I wonder if [this](https://github.com/crossplane-contrib/provider-aws/blob/27f6c4ebe90f91f55ef9fdb5cfd6e8b0d20be134/apis/rds/generator-config.yaml#L59) wouldn't be the culprit since I believe it should be `ModifyDBClusterParameterGroupInput.DBClusterParameterGroupFamily` but again, I couldn't wrap my head around how the code works anyway.

[Here's an example](https://gist.github.com/maxforasteiro/2afa545ec78af05fb31fa94df4b47ed7) of the composition that we are using to create Cluster + instance + SG + DB Cluster Parameter Group

**Comment by maxforasteiro** [comment]
Interesting enough: I applied the changes to my staging cluster and 4 out of 27 DB Clusters changed to the newly created DBClusterParameterGroup. Seems to be a racing condition with my composition 🤔 any tips on how to improve composition co-dependencies?

**Comment by maxforasteiro** [comment]
> How are you setting the `dbClusterParameterGroup` field? If it's a patch that references a creating resource then you may need to set a policy that specifies the patch as required.
> 
> For example:
> 
> ```yaml
> - type: FromCompositeFieldPath
>   ...
>   policy:
>     fromFieldPath: Required
> ```
> 
> This will ensure the reference is resolved (cluster parameter group created) before rendering the resource in the composition.

As per example provided [here](https://gist.github.com/maxforasteiro/2afa545ec78af05fb31fa94df4b47ed7) I'm simply [matching from controller](https://gist.github.com/maxforasteiro/2afa545ec78af05fb31fa94df4b47ed7#file-rds-composition-example-yaml-L56-L59)
