### ISSUE TITLE
Support tagging on creation for some resources

### ISSUE THREAD

**Issue by liubog2008** [crossplane-contrib/provider-aws#1707]
### What problem are you facing?

I hope some resources can be created with tag. It can be used to avoid the creation pending problem for some specified resources.

At least, we can fix the leak problem manually.

See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources

### How could Crossplane help solve your problem?

Add tag field into create input.

**Comment by chlunde** [comment]
@liubog2008 do you have any specific resources in mind?

**Comment by MisterMX** [comment]
Closing this issue as it is very unspecific. However, reducing the amount of AWS calls is a always a good measure. If there are any optimizations to be added please open a separate issue / PR for these. Thanks!
