### ISSUE TITLE
MSK: write bootstrap connection strings

### ISSUE THREAD

**Issue by drewwells** [crossplane-contrib/provider-aws#1711]
When MSK is provisioned, the broker information is written to the desired connection string. To connect to MSK, it's preferred to use the bootstrap TLS and bootstrap Plaintext strings. These strings should be written out as connection information. 

I'm not a kafka expert, but I don't think it's desirable to report back the broker URLs. The bootstrap connections will allow clients to discover them.

**Comment by wotolom** [comment]
ConnectionDetails are being filled with partly wrong data here: https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/controller/kafka/cluster/setup.go#L141

see example from aws console: 
![image](https://github.com/crossplane-contrib/provider-aws/assets/82590843/d316a1b0-e049-4825-9a79-da63533f25b1)

the current logic in the controller would need to also replace the beginning of the urls ('z-' to 'b-') besides the port numbers.

probably/maybe better solution would be to use [GetBootStrapBrokers](https://docs.aws.amazon.com/cli/latest/reference/kafka/get-bootstrap-brokers.html)
