### ISSUE TITLE
Crossplane ControllerConfig Deprecation

### ISSUE THREAD

**Issue by tcd156** [crossplane-contrib/provider-aws#1715]
Hello!

I was wondering, given the circumstances of Crossplane deprecating the ControllerConfig, what the plane was for this provider to use an alternative.

https://github.com/crossplane/crossplane/issues/3601

Currently, at least in our setup, we really only need the ControllerConfig in order to specify an IRSA annotation for the controller.

My apologies if this is documented or discussed elsewhere. I didn't find anything but will close if it is duplicated.

**Comment by bobh66** [comment]
[crossplane/crossplane#2671](https://github.com/crossplane/crossplane/issues/2671) tracks the replacement functionality

**Comment by tcd156** [comment]
Ok, thanks! Interesting that it would be deprecated without a replacement in place.
