### ISSUE TITLE
Add Support for Observe Only Resources

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-aws#1726]
### What problem are you facing?

We need to add support for [Observe Only resources](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#observe-only-resources). 

See this PR as an example: https://github.com/crossplane-contrib/provider-gcp/pull/503

### How could Crossplane help solve your problem?

Add support for observe only resources with a feature flag.

**Comment by chlunde** [comment]
@turkenh did you do this manually, or scriptet in any way?

**Comment by turkenh** [comment]
> @turkenh did you do this manually, or scriptet in any way?

@chlunde unfortunately manual. 
We have a [guide](https://github.com/upbound/upjet/blob/main/docs/adding-support-for-observe-only.md) and automation for upjet based ones, which you can still check to get some insights.
But for native ones, adding options to the controllers was manual.

**Comment by chlunde** [comment]
@turkenh OK, I can try to script it, unless you're already working on it?
