### ISSUE TITLE
AWS Provider - CRDs on need

### ISSUE THREAD

**Issue by dr460neye** [crossplane-contrib/provider-aws#1736]
Hi there, 
as there a multiple requests in the different crossplane projects for heavy CRD amount, i wanted to request and discuss, if it is possible to reduce the amount of CRDs on demand.

I have the following idea, but i am not sure if this will work.

Wouldnt it be enough to use environment variables and do not run the setup routine for a package here, to reduce the amount of CRDs?

https://github.com/crossplane-contrib/provider-aws/blob/2f6449c8b82fb14fb95bef251caffca7dea829d3/pkg/controller/aws.go#L189

By changing from "dynamic" setup names to static ones, it could be also possible to compare a whitelist or load all packages, as the Setup routine has an equal name.

Try still to understand the source code and entrypoint of such a change here.

What do you think?

**Comment by bobh66** [comment]
There is a lot of discussion and additional details here - https://github.com/crossplane/crossplane/pull/3939
