### ISSUE TITLE
ProviderRevision is Unhealthy, Reason is "UnhealthyPackageRevision"

### ISSUE THREAD

**Issue by KhushKia** [crossplane-contrib/provider-aws#1753]
My Crossplane package installation goes to failure state after a fresh installation. 

provider.pkg.crossplane.io/crossplane-contrib-provider-azure   True        False     xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.1 

Please help!

$ kubectl describe providerrevision crossplane-contrib-provider-azure-c2d3b29775f5
Name:         crossplane-contrib-provider-azure-c2d3b29775f5
Namespace:
Labels:       pkg.crossplane.io/package=crossplane-contrib-provider-azure
Annotations:  meta.crossplane.io/description:
                The Microsoft Azure Crossplane provider adds support for managing Azure
                resources in Kubernetes.
              meta.crossplane.io/license: Apache-2.0
              meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
              meta.crossplane.io/readme:
                `provider-azure` is the Crossplane infrastructure provider for [Microsoft
                Azure](https://azure.microsoft.com/).

                If you encounter an issue please reach out on
                [slack.crossplane.io](https://slack.crossplane.io) and create an issue in
                the [crossplane/provider-azure](https://github.com/crossplane/provider-azure)
                repo.
              meta.crossplane.io/source: github.com/crossplane-contrib/provider-azure
API Version:  pkg.crossplane.io/v1
Kind:         ProviderRevision
Metadata:
  Creation Timestamp:  2023-05-09T08:44:42Z
  Finalizers:
    revision.pkg.crossplane.io
  Generation:  1
  Managed Fields:
    API Version:  pkg.crossplane.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.crossplane.io/description:
          f:meta.crossplane.io/license:
          f:meta.crossplane.io/maintainer:
          f:meta.crossplane.io/readme:
          f:meta.crossplane.io/source:
        f:finalizers:
          .:
          v:"revision.pkg.crossplane.io":
        f:labels:
          .:
          f:pkg.crossplane.io/package:
        f:ownerReferences:
          .:
          k:{"uid":"a192d506-2a48-4753-8fb5-78877ced770f"}:
      f:spec:
        .:
        f:desiredState:
        f:ignoreCrossplaneConstraints:
        f:image:
        f:packagePullPolicy:
        f:revision:
        f:skipDependencyResolution:
        f:webhookTLSSecretName:
    Manager:      crossplane
    Operation:    Update
    Time:         2023-05-09T08:44:45Z
    API Version:  pkg.crossplane.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:controllerRef:
          .:
          f:name:
    Manager:      crossplane
    Operation:    Update
    Subresource:  status
    Time:         2023-05-09T08:44:45Z
  Owner References:
    API Version:           pkg.crossplane.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Provider
    Name:                  crossplane-contrib-provider-azure
    UID:                   a192d506-2a48-4753-8fb5-78877ced770f
  Resource Version:        360879
  UID:                     6ab2c055-d39d-4b86-8701-3ea531d6c865
Spec:
  Desired State:                  Active
  Ignore Crossplane Constraints:  false
  Image:                          xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.1
  Package Pull Policy:            IfNotPresent
  Revision:                       1
  Skip Dependency Resolution:     false
  Webhook TLS Secret Name:        webhook-tls-secret
Status:
  Conditions:
    Last Transition Time:  2023-05-09T08:44:45Z
    Reason:                UnhealthyPackageRevision
    Status:                False
    Type:                  Healthy
  Controller Ref:
    Name:
Events:    <none>

**Comment by bobh66** [comment]
I think you wanted https://github.com/crossplane-contrib/provider-azure or https://github.com/crossplane/crossplane

**Comment by haarchri** [comment]
As @bobh66 said - please create an issue in crossplane core or provider-azure thanks
