### ISSUE TITLE
How can push changes via crossplane? 

### ISSUE THREAD

**Issue by nitagarwal** [crossplane-contrib/provider-aws#1759]
the crossplane seem to reconcile new resources/update based on polling interval here : https://github.com/crossplane-contrib/provider-aws/blob/master/cmd/provider/main.go#L50 

We would like to setup a high polling interval(1d) so that we do not increase AWS bills. 
Is there a way that crossplane work on push model. So, I update the MD and push to k8s cluster and then crossplane applies those changes instantly instead of waiting 1d.

**Comment by bobh66** [comment]
Updates to the resource spec will trigger a reconciliation regardless of the polling interval.   You should be able to set the poll interval to a large value and still get changes applied immediately.

**Comment by MisterMX** [comment]
Currently, the polling interval is fixed and cannot be changed for specific resources. However it can be changed globally using the referenced CLI args. There are proposals to change this, like #1625.

Closing, as push models are not supported by the K8s controller runtime.
