### ISSUE TITLE
Respect web token locaton envrionment variable

### ISSUE THREAD

**Issue by nabuskey** [crossplane-contrib/provider-aws#1775]
### What happened?

IRSA token file location is [hardcoded in aws client](https://github.com/crossplane-contrib/provider-aws/blob/594d12c084d9642e7b0a91635dd4bd485edbaae8/pkg/clients/aws.go#L374). This makes it impossible to test it locally because this directory typically do not exist on local systems. 

IRSA uses the `AWS_WEB_IDENTITY_TOKEN_FILE` environment variable to determine the location of an OIDC ID token or oAuth access token to assume a role. We should respect it. 

Also note that in the realm of Crossplane, being able to use the token specified in `AWS_WEB_IDENTITY_TOKEN_FILE` only is likely not what we want. Currently, it is impossible for users to use a token not managed by EKS to assume a role in this provider or the upbound provider. We'll need to expand the spec and add a field to support it. 

I can work on this to remove the hardcoded value and use the environment variable value instead. 

### What environment did it happen in?
Crossplane version: master

**Comment by MisterMX** [comment]
@nabuskey this sounds like a reasonable change, although I am unsure about extending the spec. I think looking at the environment variable should be suffice here.

**Comment by nabuskey** [comment]
Thanks for the PR! Looks good other than the const location. 

I think I did a poor job of describing what I meant above because it's a bit convoluted process. I don't think what I am describing below needs to be implemented right now because it's a niche use case, but I am putting it here in case someone run into this issue in the future. 




I believe, the intention of the changes introduced for [this struct](https://github.com/crossplane-contrib/provider-aws/blob/49f83fded63a452b195b2b6daee31a5b7b3dce17/apis/v1beta1/providerconfig_types.go#L99) is to allow for the functionality described [here](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role-with-web-identity.html). In a nut shell, it allows you to assume a role using external (external to AWS) identity using a OAuth 2.0 or OIDC token provided by a trusted identity provider. 


When configuring and using EKS IRSA, general flow of events are: 
1. A EKS cluster generates and associates its own OIDC provider. 
2. IAM trusts this OIDC provider in the same account that the EKS cluster is in. 
3. EKS admission hook injects EKS OIDC token to the pod at `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` 
4. Calling `LoadDefaultConfig()` causes the SDK to exchange the token to obtain AWS credentials. 

As you can see, in a typical EKS IRSA environment, a pod is tied to the identity assured by the EKS OIDC. This works for many workloads. 

For AWS providers in Crossplane, this may not be sufficient. Let's consider the following scenarios. They both illustrate the issue of tying a pod to an identity. 

1. Provider running in non-EKS environment. 
2. Provider running in EKS environment but an account does not allow role chaining.

For the first scenario, if a user wants to use this feature, they must put the token in the location specified by the `AWS_WEB_IDENTITY_TOKEN_FILE` value. This will work as long as the same identity is trusted by all AWS accounts that they'd like to use. If the user need the provider to assume a role in another account which requires a different token, this breaks down because the only way for the provider to assume a role with a token is by using the token specified in the env var.

For the second scenario, provider works within the same account the cluster is in. It also works for multi account situation as long as the EKS OIDC is trusted by other accounts. This breaks down if a user wants to use EKS OIDC for the account but wants to use different identity (token) for other accounts because there is no way for the provider to assume a role using different tokens than what is specified in the env var. 

I think you can solve these by allowing users to specify token location in provider config. By doing this, we are tying an identity to a provider config. Something like:

```go
type AssumeRoleWithWebIdentityOptions struct {
	RoleARN *string `json:"roleARN,omitempty"`
	RoleSessionName string `json:"roleSessionName,omitempty"`
        WebIdentityToken string `json:"webIdentityToken"`
        SessionDuration string `json:"sessionDuration"`
}
```

Again, I think for the vast majority of users, being able to use the `AWS_WEB_IDENTITY_TOKEN_FILE` var will suffice, and I don't think it's something we need to work on right now.
