### ISSUE TITLE
DBInstance: InvalidParameterCombination: The specified DB Instance is a member of a cluster. Modify vpc security group for the DB Cluster using the ModifyDbCluster API

### ISSUE THREAD

**Issue by cm3brian** [crossplane-contrib/provider-aws#1799]
### What happened?

While trying to modify the rds (aurora) instance type of a cluster-owned db instance, an error occurred: 
`update failed: cannot update DBInstance in AWS: InvalidParameterCombination: The specified DB Instance is a member of a cluster. Modify vpc security group for the DB Cluster using the ModifyDbCluster API`
further reading produced, amongst other aligned issues, #1285 #1286 
Reading of the AWS docs shows that you may not alter VPC Security Groups  on instances as a part of a cluster:
https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-instance.html#:~:text=Amazon%20Aurora%20(The%20associated%20list%20of%20EC2%20VPC%20security%20groups%20is%20managed%20by%20the%20DB%20cluster

### How can we reproduce it?

Try and modify an existing cluster instance; in our case, we are trying to update the instance class.

### What environment did it happen in?
Crossplane version: v1.12.2
provider-aws version: v0.41.1

**Comment by MisterMX** [comment]
Looks like it needs a check in `DBInstance`'s `preUpdate` to determine whether this instance is part of a cluster. I believe this required `DBClusterIdentifier` to be added to `DBInstanceObservation`. The value is already delivered by AWS as part of the `DescribeDBInstances` response.

**Comment by eloo-abi** [comment]
> However, the quick way to avoid this problem would be to not set spec.forProvider.vpcSecurityGroupIDs at all.

i guess this is not a proper solution :D 

the vpcSecurityGroupIDs must be included in this block
https://github.com/iAnomaly/provider-aws/blob/1fd900eb76877bf4f83faf59df4bd9eb0f4d94a7/pkg/controller/rds/dbinstance/setup.go#L207

as a proper workaround:

manually remove the `spec.forProvider.vpcSecurityGroupIDs` from your dbinstance if this instance is part of a dbcluster using `kubectl edit` for example
