### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by chlunde** [crossplane-contrib/provider-aws#1839]
We need an updated README and marketplace entry on https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.42.0 updated to clearly reflect the state of how this project is maintained and the alternatives, to ensure users make a correct and informed choice of provider.

I think the active maintainers, currently @MisterMX and I should agree on some wording about how issues and new feature requests are handled. Roughly, we maintain the features that are here, but PRs for new resource types and maintenance of the is welcome. Ideally we can get some help from Upbound, like @jeanduplessis, to have a good well balanced text for new end users regarding choice of provider. The text should probably be fairly static so it does not need updating.

At least, we should avoid having users pick this provider because of a misunderstanding the license of the upjet provider.

**Comment by jeanduplessis** [comment]
I'd be happy to assist here.
