### ISSUE TITLE
[Route53] Support multiple Zone IDs in spec

### ISSUE THREAD

**Issue by Ethan-99** [crossplane-contrib/provider-aws#1853]
### What problem are you facing?

In the `ResourceRecordSet` resource, the name of the resource is the name of the record. This is all well and good, unless you want to be able to create more than one record of the same name in different zones. Say I have an ArgoCD app and a r53 record controlled by that app. I want to put this record in both Zone A and Zone B. I am unable to create two instances of `ResourceRecordSet` because the names of the resources are the same, and you can only provide one Zone ID to place the record in the resource object.

### How could Crossplane help solve your problem?

It would be great if this can be supported by implementing the following to the resource manifest:

Add a new optional parameter to the `ResourceRecordSet` resource called `zoneIds` or something similar that accepts a list of zone IDs to create the record. Add constraints such that only one of `zoneId`, `zoneIds`, `zoneIdRef`, or `zoneIdSelector` may be defined.

**Comment by haarchri** [comment]
you can use crossplane.io/external-name annotation then you can set metadaten.name to random string

**Comment by Ethan-99** [comment]
@haarchri Thank you, exactly what I needed. Did not realize this functionality was available.
