### ISSUE TITLE
Unable to remove VPC & Environment Variables from Lambda

### ISSUE THREAD

**Issue by DiogoRoloOS** [crossplane-contrib/provider-aws#1872]
### What happened?
Removing the configurations from CustomFunctionVPCConfigParameters should be able to remove the VPC from AWS. It doesn't.
To remove the VPC we have to set the SecurityGroupIDs and SubnetIDs as empty, according to the AWS docs.
Looking at the [code](https://github.com/crossplane-contrib/provider-aws/blob/29651ece73cdd17c6ce9a76ae054c273e1018ef7/pkg/controller/lambda/function/setup.go#L554-L573), if we set CustomFunctionVPCConfigParameters parameter as nil, it doesn't even enter the check to remove the VPC. If we set it as empty object, we also have to set SecurityGroupIDs and SubnetIDs  as empty objects, since the code is checking for nil. We can't set them as empty objects since they are arrays and the json marshaller configuration is set to omit empty.

Basically, we need to have the following yaml in the CR to remove the VPC from an existing lambda:
```
vpcConfig:
  securityGroupIDs: []
  subnetIDs: []
```
but with the current code, the closest we get is:
```
vpcConfig: {}
```

Similar case is happening to Environment:Variables. We can set the Environment as empty object, but we can't set the Variables as empty (due to the omit empty in the marshaller and nil check in the code) so we can't remove environment variables.

If we edit the yaml manually, to set those parameters as empty (we can do that since we don't have to follow the json marshal rules manually =D only the CRD rules), we can remove the resources as expected.

### How can we reproduce it?
Create a Lambda with an environment variable
Try to remove environment variable via code.

OR
Create a Lambda with a VPC configuration
Try to remove the VPC configuration via code.

### What environment did it happen in?
Crossplane version: v0.42.0
K8s 1.25 - EKS

I'm not sure if the correct route would be to change the json definition to allow empty objects or to change the code to set them if nil

**Comment by MisterMX** [comment]
I guess the easiest solution for this is to just remove the nil checks in the controller so an empty array / map will be pushed in case the value is nil.
