### ISSUE TITLE
ACM Certificate and Corresponding Validating record in HZ does not work when creating custom xrd + composition

### ISSUE THREAD

**Issue by rushrs** [crossplane-contrib/provider-aws#1916]
### What happened?

I created a custom composition which creates a ACM Certificate and passes information generated from it's creation into the corresponding HZ as a validation record. I run into an issue where the external name is invalid in all circumstances for the Validating record as it is inherited from the composition. this prevents the route53 record from being recorded. if I manually update this value after the fact it can work.

### What environment did it happen in?
Crossplane version:

**Comment by MisterMX** [comment]
Could you please share some more information, like the YAML of the MRs?
