### ISSUE TITLE
ACM Import certificate

### ISSUE THREAD

**Issue by jlpedrosa** [crossplane-contrib/provider-aws#1927]
### What problem are you facing?
Currently the resource [Certificate](https://doc.crds.dev/github.com/crossplane/provider-aws/acm.aws.crossplane.io/Certificate/v1beta1@v0.44.0),  allows the creation of new certificates through ACM, but does not allows importing existing certificates.

This is required to use pre-existing certificates in Loadbalancers. 

### How could Crossplane help solve your problem?
Either by augmenting the Certificate or through a new CRD `ImportedCertificate` that would have fields in it's spec to set the content of the certificate to import.

**Comment by MisterMX** [comment]
Does this refer to existing ACM certificates that should be tracked through the MR by setting the external name annotation or the important of external certificates into ACM?

**Comment by simon-wessel** [comment]
/fresh

This would solve a feature gap of [kubernetes-sigs/aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller). See issue #1084.
