### ISSUE TITLE
How to reference a new ec2 to a new TargetGroup dynamically 

### ISSUE THREAD

**Issue by devopsmash** [crossplane-contrib/provider-aws#1950]
What is the best approach to create a new ec2 instance, and then reference this ec2 instance to TargetGroup ?

I can see [here](https://doc.crds.dev/github.com/crossplane/provider-aws/elbv2.aws.crossplane.io/TargetGroup/v1alpha1#spec-forProvider-targetType)  that there is `targetType` that I can use for static ec2 `instance id` or  `ip` (and more), but there is no any `ec2IdRef` or something similar (like `vpcIdRef` or other object references).

Do you plan to support it? any other idea of how to referenca a new ec2 instance to a target group dynamically ?

**Comment by MisterMX** [comment]
No referencers for `spec.forProvider.targetType` have been implemented so far. We have no plan to work on it by ourselves but we are open to accept a PR if you want to work on it.
