### ISSUE TITLE
Dynamic AMI Lookup in Crossplane AWS Provider

### ISSUE THREAD

**Issue by ehsanhedayatpour** [crossplane-contrib/provider-aws#1963]
I'm requesting a new feature in the Crossplane AWS Provider that enables dynamic AMI lookup. This feature would allow users to dynamically discover the latest AMIs without hard-coding specific AMIs in the manifests.

Currently, in Terraform, I use a dynamic approach to get the latest Ubuntu AMI:

<img width="763" alt="ami" src="https://github.com/crossplane-contrib/provider-aws/assets/29874484/0b49c8f9-d870-49a5-9bc4-4bd375dbef0b">

Thanks for considering this feature request! If you need more details, I'm happy to help.

**Comment by fmunteanu** [comment]
@ehsan-hedayatpour I believe you can use the Terraform [provider](https://github.com/upbound/provider-terraform) to achieve your goal. I’m looking for a similar solution.

**Comment by bobh66** [comment]
provider-terraform is definitely an option, and you could also use a Composition Function to retrieve the data for you.
