### ISSUE TITLE
Support eks pod identity association

### ISSUE THREAD

**Issue by brandocomando** [crossplane-contrib/provider-aws#1972]
### What resource do you need?
Aws recently announced eks pod identities. I'd like to use it via crossplane.
https://docs.aws.amazon.com/eks/latest/userguide/pod-id-association.html

Specifically what is missing is the equivalent of this aws CLI command
`aws eks create-pod-identity-association --cluster-name my-cluster --role-arn arn:aws:iam::111122223333:role/my-role --namespace default --service-account my-service-account`

### What is your use case?
Instead of linking service accounts to iam roles via oidc configuration I'd like to use pod identity

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)
I'll take a look.

**Comment by jmalloc** [comment]
In addition, it would be great to support pod identities as an authentication method in `ProviderConfig`

**Comment by wesleyorama2** [comment]
/fresh

This is also important to us as well. This is pretty much the only reason we are not using crossplane right now.

**Comment by fhochleitner** [comment]
/fresh would love to have this feature

**Comment by jmerciercode** [comment]
/fresh

Would be nice

**Comment by MisterMX** [comment]
Hey, folks, quick update on the status of this issue:

Since this provider is kind of in maintenance mode and we don't have the time to provide full support we (as maintainers) are not going to implement this and other features on our own. However, we do accept pull requests to include new features into the provider. So feel free to start working on it and assign one of us as reviewer.

**Comment by SleepyBrett** [comment]
/fresh 

This might be something I could take on however I would like to consult with one of the maintainers about the shape of this work. Is there someone who would be willing to chat?
