### ISSUE TITLE
Allow use of EKS pod identities as an authentication method

### ISSUE THREAD

**Issue by jmalloc** [crossplane-contrib/provider-aws#1981]
### What problem are you facing?

I would like to use EKS pod identities to grant the provider access to AWS, as an alternative to IRSA

### How could Crossplane help solve your problem?

By adding support for this authentication method in `ProviderConfig`.

FWIW, I did attempt to use a pod identity with a `ProviderConfig` set to use `IRSA` credentials, hoping that it might "just work" given that both IRSA and pod identities work by automatically injecting AWS environment variables into the pod. This approach failed, but I no longer have the exact error message, sorry. Some googling at the time suggested that it might be necessary to use version 2 of the AWS Go client with EKS pod identities.

**Comment by hsmade** [comment]
From what I can find with other controllers with the same issue, all that needs to be done is updating the aws sdk dependency.

Examples: [1](https://github.com/aws-controllers-k8s/community/issues/1953) [2](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1870)

**Comment by fhochleitner** [comment]
/fresh would also love to have this feature
