### ISSUE TITLE
Tags are not updated for rdsinstance resource on update operation

### ISSUE THREAD

**Issue by Savasw** [crossplane-contrib/provider-aws#1982]
### What happened?
i created an `rdsinstance.database.aws.crossplane.io` resource with some tags and other dependent resources (sg, subnetgroup,dbparametergroup). The newly created resource had required tags but when i went and updated the `rdsinstance` k8s resource with new tags and update of existing ones, the changes were never synced with no issues or error reported. Although the same updates on the dependent resources worked fine and i could see updated tags on aws side for them but not for rds resource.

### How can we reproduce it?
- Create an `rdsinstance.database.aws.crossplane.io` resource with some tags and wait for creation on aws side.
- update the same k8s/crossplane resource with new additional tags or update existing tags. The resource on aws side is never updated with new/updated tags.

### What environment did it happen in?
- Crossplane version: v1.14.2
- AWS provider release: v0.45.0
- Cloud provider - AWS
- Kubernetes version - v1.27
- Kubernetes distribution - AWS EKS

**Comment by wotolom** [comment]
This bug should been fixed with provider-aws v0.46.0.
See this closed issue https://github.com/crossplane-contrib/provider-aws/issues/1962
