### ISSUE TITLE
Dynamically referencing the ARN of Lambda Layer in Lambda Function

### ISSUE THREAD

**Issue by poliveirabp** [crossplane-contrib/provider-aws#2012]
Hi, there is any way i can do that? So basically i want to use the ARN of the Lambda Layer in the layers field dynamically on Lambda Function, like how works in terraform where we can mention the ARN of a created resource.

**Comment by MisterMX** [comment]
`spec.forProvider.layer` currently does not have a referencer implementation (-`Ref` and -`Selector` fields). One would have to add that to be able to set the layer ARNs dynamically.
