### ISSUE TITLE
S3 Bucket constantly calls PutBucketNotification with NotificationConfiguration

### ISSUE THREAD

**Issue by Yaswanth45** [crossplane-contrib/provider-aws#2013]
### What happened?

I have created a S3 bucket with notificationConfiguration(TopicConfiguration), when i checked the cloudTrail logs putBucketNotification is being triggered/called every minuted by the crossplane/provider. Seems it is the similar issue which was fixed for QueueConfiguration https://github.com/crossplane-contrib/provider-aws/issues/1165 .

### How can we reproduce it?

Create a bucket and configure SNS topic as a notificationConfiguration. check cloudTrail logs, PutBucketNotification event will be triggered on every minute.

### What environment did it happen in?
Crossplane version: 1.14.5
Provider version: 0.46.0

**Comment by wotolom** [comment]
Should be fixed in `v0.48.1`. 
Would be nice, if you could confirm that :)
