### ISSUE TITLE
Unable to create EKS Cluster using crossplane managed resources

### ISSUE THREAD

**Issue by vignesh-vicky-tech** [crossplane-contrib/provider-aws#2022]
![image](https://github.com/crossplane-contrib/provider-aws/assets/85112276/a3d6d219-0839-47cf-b521-51bf64f27cef)
aws-eks provider installed

Output:
![image](https://github.com/crossplane-contrib/provider-aws/assets/85112276/b4077b2f-39c5-46ee-80a1-faa0c4c3d50b)

Expected Output:
EKS cluster should be created

eks-cluster.yaml:
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    uptest.upbound.io/timeout: "2400"
  name: dev-demo
spec:
  forProvider:
    version: "1.29"
    region: us-west-1
    roleArnRef:
      name: EKS_cluster_accessrole
    vpcConfig:
      - endpointPrivateAccess: false
        endpointPublicAccess: true
        subnetIdRefs:
          - name: dev-public-us-west-1b
          - name: dev-public-us-west-1c
  providerConfigRef:
     name: default

eks-nodegroup.yaml:
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: demo
spec:
  forProvider:
    clusterNameRef:
      name: dev-demo
    nodeRoleArnRef:
      name: dev-demo-eks-nodes
    region: us-west-1
    instanceTypes: ["t2.small"]
    scalingConfig:
      - desiredSize: 1
        minSize: 1
        maxSize: 1
    subnetIdRefs:
      - name: dev-public-us-west-1b
      - name: dev-public-us-west-1c
~

**Comment by bobh66** [comment]
The MR is not synced - you should be able to run `kubectl describe` on the cluster MR to see what the problem is.  Also debug logs in the provider should give more information.

**Comment by vignesh-vicky-tech** [comment]
It worked after using an IAM Role and Policy that is created using Crossplane
