### ISSUE TITLE
Cognito User username

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/provider-aws#2089]
### What happened?

I'm trying to create a  [Cognito User](https://marketplace.upbound.io/providers/upbound/provider-aws-cognitoidp/v1.13.0/resources/cognitoidp.aws.upbound.io/User/v1beta1) and AWS requests are without username field.

The User resource doc shows **there is no** field called `username ` or similar.

I tried to use the attributes field as follows:
```yaml
attributes:
  username = test@example.com
```
but I still get the AWS request error shown below:
`"errorMessage": "Username should be an email.",`

### How can we reproduce it?

Try to create a Cognito User

### What environment did it happen in?
Crossplane version: 1.17.0

Kubernetes version (use `kubectl version`) 1.30
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) EKS

**Comment by irizzant** [comment]
Any update on this?

**Comment by MisterMX** [comment]
Hi,

you want to ask that at https://github.com/crossplane-contrib/provider-upjet-aws which is the terraform based AWS provider for Crossplane. It contains all resources in `*.aws.upbound.io`.

This is the legacy, community-maintained provider built on the AWS SDK that has the API group `*.aws.crossplane.io`.
