### ISSUE TITLE
LaunchTemplate UserData Patching/Transforming Not Working

### ISSUE THREAD

**Issue by hhami-newday** [crossplane-contrib/provider-aws#2094]
### What problem are you facing?
I am having issues with LaunchTemplates and patching/transforming the user-data within Compositions. 

More specifically, I would like to include some details generated by other resources that are created in the Composition (for example, EKS Cluster server endpoint etc).

So this would involve:
- Combining and formatting the various elements from `status.*`
- Base64 encoding the above and giving it to the user data field

I cannot seem to get that to work. The status shows no errors, just the userdata remaining blank. If I choose a more simple operation, I can place a string into userdata (which it will then obviously complain it isn't base64 encoded). 

### How could Crossplane help solve your problem?
I am finding it hard to get any examples similar to mine above that involve both manipulating outputs from other resources AND encoding it before populating the field which _requires_ the encoding. 

I can't imagine this is a unique scenario to perform so having that documented would be useful. Any pointers to where this info would be, if I missed it, please feel free to correct me.

**Comment by hhami-newday** [comment]
I eventually solved this but took much longer than it should have. I think maybe extended examples of sharing values across resources in Compositions would be valuable.

**Comment by MisterMX** [comment]
Patch and transforms are a feature of core Crossplane itself which lives in its own repo: https://github.com/crossplane/crossplane. The providers itself do not contain such logic and only expose resource information in the status field.

You might also want to check out the Crossplane docs that provide more insights on how to write patch and tranforms: https://docs.crossplane.io.
