### ISSUE TITLE
Add Auto Scaling Group as a managed resource

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane-contrib/provider-aws#237]
### What problem are you facing?
For stacks using EC2 instances aiming for auto-scaling, Auto Scaling Group is a service provided by AWS

### How could Crossplane help solve your problem?

This provider can have Autoscalingroup as a managed resource to provision amd manage AWS Auto Scaling Groups

**Comment by bencouture** [comment]
I'm interested in working on adding this resource. I've started looking at the docs for generating and contributing, and they say I should communicate my intent to reduce duplicate effort and make sure there isn't some special consideration to take into account. Is anybody working on this already?

**Comment by jbw976** [comment]
@bencouture I'm not aware of anyone already working on this issue as I see no one already assigned to it and I don't see any open PRs.  If you want to start development on this, then that should be totally reasonable and we can get you assigned to it.

One thing to note is that there is now support for ASG in the provider-jet-aws, see the generated docs for this resource at https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/autoscaling.aws.jet.crossplane.io/AutoscalingGroup/v1alpha2@v0.4.1. 

Would this work for your scenario? Especially in the light of the potential merging of jet and classic providers as discussed in https://github.com/crossplane/crossplane/pull/2930 :)

**Comment by celalettin1286** [comment]
Hi @haarchri 

May I ask is this issue completed because managed resource for ASG already developed(I couldn't see the ASG CRD though) or because provider-jet-aws has the ASG managed resource?
