### ISSUE TITLE
Add AWS EMR Cluser as a managed resource

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane-contrib/provider-aws#239]
### What problem are you facing?

EMR is a managed service from AWS for processing vast amounts of data using open source tools such as Apache Spark, Apache Hive.
Having a managed resource that can provision an EMR can help users from the big data community to manage their clusters.

### How could Crossplane help solve your problem?

EMR has a various supported features, we can start with an EMR cluster as a managed reousrce in this provider, which will provision and manage AWS EMR Cluster.

**Comment by pthatchinamoorthy** [comment]
Curious, is this Issue opened for both "EMR on EC2" and "EMR on EKS" ?

**Comment by sahil-lakhwani** [comment]
hey @pthatchinamoorthy, I had opened this for just EMR on EC2 then
