### ISSUE TITLE
S3 Bucket provisioning should include Permission boundary attachement during iam user creation

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane-contrib/provider-aws#269]
### What problem are you facing?
I have a policy restriction on iam user creation for my organization and it required us to attach pre-defined PermissionBoundary

Understand that S3 Bucket provisioning controller did create iam user with permisson to allow user accessing the bucket using API Access Key and Secret (https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateUser.html)

### How could Crossplane help solve your problem?

To include the parameter for PermissionBoundary to allow user to attach the arn
Refer to PermissionBoundary parameter from : https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateUser.html

Another recommendation is to have IAMUserRef which refer to the IAMUser that is created through crossplane (which is more preferred) as we can have more control of what IAM and Policy we want to attach to as refined as possible

**Comment by muvaf** [comment]
Hi @kelvinwijaya ! S3 bucket is one of the oldest controllers and [in the queue](https://github.com/crossplane/provider-aws/issues/99) to be updated to our latest runtime capabilities and specifically to have the granularity you'd like. Feel free to show your support on that issue!

**Comment by kelvinwijaya** [comment]
Hi @muvaf 

Thanks for the update on the product roadmap, may i know if someone has taken this enhancement task up? 
As when time permit, i would see how i can support on this issue, so i assume the guidelines are describe in the contributing section

**Comment by muvaf** [comment]
@kelvinwijaya Yeah, you're more than welcome! As addition to contributing section, you can take a look at the following sources to get to up to speed quickly:
* Managed Resource Development Guide - https://crossplane.io/docs/v0.12/contributing/services_developer_guide.html
* The Youtube episode where we implemented GCP PubSub Topic resource live - https://www.youtube.com/watch?v=rvQ8N0u3rkE

**Comment by kelvinwijaya** [comment]
Hi @muvaf , Thanks for the pointers. these will be helpful

**Comment by kelvinwijaya** [comment]
Hi @muvaf ,

Just to clarify, when we moved to s3 v1beta1 release, does that mean the user auto creation flow will stay put?

Reason i am asking is if we kept the user creation flow, how do we pass the permission boundary information in S3 Bucket CR as it is no longer by IAMUser reference?

Thanks,
Kelvin

**Comment by muvaf** [comment]
Hi @kelvinwijaya . In its v1beta1 version, S3 controller will not create a user anymore. I believe, you'd need to use `IAMUser` managed resource to manage an IAM user and put any permission boundary information on that CR.

**Comment by kelvinwijaya** [comment]
Hi @muvaf , ok thanks for the clarifications!

**Comment by haarchri** [comment]
@kelvinwijaya is this issue solved ? Or did you thinks Iit is still relevant ?
