### ISSUE TITLE
Egress and Ingress rules should be separate from SecurityGroup

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#297]
### What happened?

SecurityGroup object has arrays for both ingress and egress rules but according to our [managed resource API design](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#high-fidelity), they should be separate CRDs.

**Comment by muvaf** [comment]
I am not 100% sure about this as these rules do not have anything to identify them at all. It's literally the set of all properties that make up an identifier and this argument could go for any array element of all managed resources.

**Comment by muvaf** [comment]
FWIW, deletion of `SecurityGroup` also deletes all `Ingress` and `Egress` rules. So, in case we did separate them into their own types, we'd see leftover rules in the cluster whose `SecurityGroup` doesn't exist anymore.

**Comment by haarchri** [comment]
We have SecurityGroupRule since Release v0.30.0
