### ISSUE TITLE
S3 Bucket - Full ACL Support

### ISSUE THREAD

**Issue by krishchow** [crossplane-contrib/provider-aws#362]
### What problem are you facing?

I would like to have access to the full breadth of ACL functionality for an S3 Bucket. Currently, I can pass in a canned ACL, but I cannot update my ACL values.
### How could Crossplane help solve your problem?

Crossplane, more specifically the provider-aws, should have support for all the ACL functionality from AWS.

**Comment by MisterMX** [comment]
ACLs are considered deprecated by AWS and bucket policies should be used instead. I don't know if it is worth the effort of implementing this.
