### ISSUE TITLE
Support day 2 operations features for backing services

### ISSUE THREAD

**Issue by gowrisankar22** [crossplane-contrib/provider-aws#367]
### What problem are you facing?
Support for “day 2” operations that developers might want for backing services(rds, cache, etc) e.g backup(Available) and restore(not available), credentials rotation(not avilable) ..etc

https://github.com/crossplane/provider-azure/issues/178
https://github.com/crossplane/provider-gcp/issues/265
same for alibaba as well.

### How could Crossplane help solve your problem?
Implementing CRDs and controllers for the relevant services on each cloud.

**Comment by muvaf** [comment]
Hi @gowrisankar22 ! Could you give more details about what you mean by day 2 operations? It's unlikely that provider-aws will have features that AWS doesn't offer, so, I would like to understand which AWS APIs you mean and open targeted issues about those APIs.

**Comment by gowrisankar22** [comment]
@muvaf Day2 operations I meant in addition to just crud operations, additionally backup, restore, credential rotation, monitoring, logging ..etc are very much important for the effective software system. 

Of course, cross-plane is completely API driven from hyper scalers, mostly all the hyperscalers are having day2 operation APIs in place, just we need to integrate this via crossplane.

This would be applicable for any services but I advocate for backing services. Below are the few things that should be available on all the infra, to do the abstraction in an efficient way.

Backing Service day2 operations | aws | azure | gcp | ali
-|-|-|-|-
backup | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark:
restore | :warning:  | :warning:| :warning: | :warning:
upgrade | :white_check_mark: | :warning: | :warning: | :warning:
credential roation | :white_check_mark: | :warning: | :warning: | :warning:
Multiaz | :white_check_mark:  | :warning: | :white_check_mark:  | :warning:
Encryption | :white_check_mark:  | :warning: | :white_check_mark:  | :warning:
integration to kv store | :warning: | :warning: | :warning: | :warning:

**Comment by haarchri** [comment]
think for all of this resources it is possible to create day2 providers to manage it

**Comment by MisterMX** [comment]
Backup and restore is implemented for the following MRs:

- [x] `DBInstance.rds.aws.crossplane.io`
- [x] `DBCluster.rds.aws.crossplane.io`
- [x] `RDSInstance.database.aws.crossplane.io`
- [x] `DBCluster.docdb.aws.crossplane.io`
- [x] `CacheCluster.cache.aws.crossplane.io`
- [x] `ReplicationGroup.cache.aws.crossplane.io`

I am closing this now since the requirements of this issue seem to be fulfilled. Feel free to reopen if that is not the case.
