### ISSUE TITLE
Implement Simple Email Service (SES) resources

### ISSUE THREAD

**Issue by marcinc** [crossplane-contrib/provider-aws#414]
### What problem are you facing?

AWS Provider does not have support for SES resources.

### How could Crossplane help solve your problem?

Implement SES resources.

**Comment by ikarldasan** [comment]
Any progress on this issue? I would like to help with this resource

**Comment by kelvinwijaya** [comment]
Hi there,

I would like to contribute on this resource if no one has started on the controllers logic yet. I have some working code that I have developed for `EmailIdentity` and `ConfigurationSet` Resources using AWS SESv2 Service API, thinking adding another functionality for `ConfigurationSetEventDestination` Resource and probably can be a good start for v1alpha1 release

**Comment by kelvinwijaya** [comment]
Hi @luebken @ikarldasan ,

Would you mind if i help on the development of the SES resource as my project needs to leverage on and have short timeline for this? 

Apologise if i have repeated the same request, as i have already done some wireframe of the custom resource and written the controller logic . So thinking of contributing them since I am leveraging heavily on crossplane for other managed resources

**Comment by ikarldasan** [comment]
Hi @kelvinwijaya 
Yes definitely. Would be great to get your help 

Would like to mention that I am currently working on improving the PR for SES Template (https://github.com/crossplane/provider-aws/pull/755).

Thank you

**Comment by kelvinwijaya** [comment]
Thanks @ikarldasan 

What I am planning as the first cut (v1alpha1) would be the 3 main resources:
- EmailIdentity
- ConfigurationSet
- ConfigurationSetEventDestination

Yes thanks for highlighting and I do notice your PR on the SES Template (which is based on SESv1 API). This might potentially be helpful when rendering `EmailTemplate` resource for SESv2 which i hit into error: `pkg conversion - executing "sdk_find_read_many"`

Just to highlight that I will be using the SESv2 API which I think is more simplified. Both version has slightly differences in the resource names [link](https://github.com/aws/aws-sdk-go/tree/v1.37.4/models/apis) but functionality wise are quite similar as i hv switched my AWS Web Console to v2 and my data is transitioning smoothly.

**Comment by kelvinwijaya** [comment]
Thanks @jbw976 for assigning this ticket, let me know if any further help or needs for amending the respective PR
