### ISSUE TITLE
Generate SNS services using ACK

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#451]
### What problem are you facing?

SNS is available in ACK code generation pipeline but we haven't generated it.

### How could Crossplane help solve your problem?

Implement missing pieces in Crossplane pipeline in ACK to get SNS services. We have some SNS resources available but they should be replaced with generated one without losing any functionality.

**Comment by luebken** [comment]
Codegen fails for me: 

```
10:37:40 [ .. ] Generating sns controllers and CRDs
Error: template: /Users/mdl/workspace/crossplane-github/provider-aws/.work/code-generator/templates/crossplane/pkg/conversions.go.tpl:6:3: executing "sdk_find_get_attributes" at <GoCodeGetAttributesSetInput .CRD "cr" "res" 1>: error calling GoCodeGetAttributesSetInput: called SetSDKGetAttributes for a resource 'PlatformApplication' that doesn't unpack attributes map
exit status 1
make: *** [services] Error
```

**Comment by tkaesserfm** [comment]
bump, getting the same
