### ISSUE TITLE
ACK should generate reference and selector fields

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#484]
### What problem are you facing?

ACK does not generate reference and selector fields. It adds a `Custom{CRDName}Parameters` field as inline and expects you to create that struct and add your ref & selector fields. This causes generated code not to compile as is and also requires developer to write `Custom{CRDName}Parameters` struct even if it's actually empty.

### How could Crossplane help solve your problem?

ACK can actually add those fields, however, it needs to know which fields are reference-able. So, developer input will be needed to list which fields should have two additional fields as referencer and selector. After that, we'll likely not need `Custom{CRDName}Parameters` anymore and it can be deleted, which gets the generated code into compile-able state.

**Comment by muvaf** [comment]
@haarchri No, that PR only generates the resolver function if the fields are marked. https://github.com/aws-controllers-k8s/code-generator/pull/246 should help us mark the fields and then have the pipeline generate the rest.

**Comment by haarchri** [comment]
@muvaf ACK PR is merged
