### ISSUE TITLE
Add Support for AWS Load Balancer Listener Rules

### ISSUE THREAD

**Issue by rayterrill** [crossplane-contrib/provider-aws#508]
### What problem are you facing?

Would love to see support for AWS Load Balancer listener rules.

### How could Crossplane help solve your problem?

We use these with Kubernetes clusters to provide OIDC support for downstream services. This would allow us to manage that process end to end.

**Comment by muvaf** [comment]
Hi @rayterrill ! I just tested generating this resource using [AWS code-gen pipeline](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md) and it seems to be supported, so we'd need only the custom parts. Would you be interested in contributing?

Out of curiosity, are you using the existing `ELB` and `ELBAttachment` CRDs already?

**Comment by saiharsha-plivo** [comment]
@muvaf can I look into this , will follow the guide in the repo (https://github.com/crossplane-contrib/provider-aws/blob/master/CODE_GENERATION.md)
