### ISSUE TITLE
Remove Provider CRD

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#520]
### What problem are you facing?

`Provider` CRD has been deprecated in favor of `ProviderConfig` and its name overlaps with `Provider.pkg.crossplane.io` in core Crossplane.

### How could Crossplane help solve your problem?

It's been marked deprecated for a few releases now, we should delete the CRD.

**Comment by hasheddan** [comment]
@muvaf this will be addressed in #518 as the crossplane-runtime update necessitates it 👍

**Comment by haarchri** [comment]
@hasheddan  @muvaf  can we do the stuff with v0.25/v0.26 ?

**Comment by haarchri** [comment]
@muvaf can we go forward  to remove and cleanup ?
