### ISSUE TITLE
Feature: Implement /scale subresource to allow resource autoscaling

### ISSUE THREAD

**Issue by tomkerkhove** [crossplane-contrib/provider-aws#537]
### What problem are you facing?

Autoscaling Azure resources can be hard and would be nice to have it integrated.

### How could Crossplane help solve your problem?

KEDA is an application autoscaler for KEDA which allows you to autoscale anything, as long as it supports /scale subresource.

If this provider would support it, we could automatically scale resources based on metrics such as Cloud Watch.

**Comment by framctr** [comment]
/fresh

Useful also for managing OpenStack resources.
