### ISSUE TITLE
Add S3 object lock configuration

### ISSUE THREAD

**Issue by yshu2017** [crossplane-contrib/provider-aws#539]
### What problem are you facing?

User need set up the object lock configuration of S3 bucket such as retention period and legal hold.

### How could Crossplane help solve your problem?

Currently provider-aws only supports the object lock flag, but not the configuration content. With this new feature, user can configure the object lock details.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-console.html

**Comment by jbhennin** [comment]
Appears these apis are needed to complete this request:

https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutObjectLegalHold
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutObjectLockConfiguration

**Comment by JaanJah** [comment]
/fresh Hi, I would also be interested in having this configuration available for object lock.
