### ISSUE TITLE
Allow users to specify the name of the provider-aws service account 

### ISSUE THREAD

**Issue by patjones** [crossplane-contrib/provider-aws#607]
### What problem are you facing?
Hi there! I am trying to automate the install of crossplane with argocd on openshift across different environments. One issue I have is that openshift requires me to attach the anyuid cluster role to the service accounts that will be spinning up pods. It's pretty straightforward to provide a clusterrolebinding for the crossplane and rbac-manager service account but the uuid appended provider-aws service account is more problematic. I'm aware it's possible to specify a completely different service account to use with a controller config, but noticed that the clusterrole that provider-aws uses is also uuid appended and I'd have to manage my own. My concern is that it seems like bad idea to try and manage the clusterrole for the aws provider as I imagine it will be changing often with the addition of new aws services, etc.

### How could Crossplane help solve your problem?
I believe letting users specify the name of the service account that gets spun up for a provider would be extremely helpful in this openshift specific situation but would love to hear any other ideas. Thank you for taking the time to read this!

**Comment by MisterMX** [comment]
Closing as this is not an issue specific to this provider but rather something that belongs to github.com/crossplane/crossplane.

Choosing the SA name can be done in the [`ControllerConfig`](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.12.2#spec-serviceAccountName) (which is a generic Crossplane resource.
