### ISSUE TITLE
Delete error messages contains session name which is unique and causes too fast reconcile

### ISSUE THREAD

**Issue by chlunde** [crossplane-contrib/provider-aws#621]
### What happened?
We tried to harden the crossplane IAM role to only be able to delete roles tagged with crossplane. When we had a bug in the policy we noticed that crossplane tried to delete it very frequently, not just once per minute. We believe this is because unix nano is used for role session name:
```
56m         Warning   CannotDeleteExternalResource   iamrole/test-a2                                                              failed to delete the IAMRole resource: AccessDenied: User: arn:aws:sts::123:assumed-role/eu-north-1-dev-crossplane/1618224507550019424 is not authorized to perform: iam:DeleteRole on resource: role real-test-a
56m         Warning   CannotDeleteExternalResource   iamrole/test-a2                                                              failed to delete the IAMRole resource: AccessDenied: User: arn:aws:sts::123:assumed-role/eu-north-1-dev-crossplane/1618224508598319228 is not authorized to perform: iam:DeleteRole on resource: role real-test-a
56m         Warning   CannotDeleteExternalResource   iamrole/test-a2                                                              failed to delete the IAMRole resource: AccessDenied: User: arn:aws:sts::123:assumed-role/eu-north-1-dev-crossplane/1618224509665648870 is not authorized to perform: iam:DeleteRole on resource: role real-test-a
...
```

SDK v1: https://github.com/aws/aws-sdk-go/blob/3961e6ef50ca64ae09f0e935f7aa7ffbffde5f5b/aws/credentials/stscreds/web_identity_provider.go#L116-L120
https://github.com/crossplane/provider-aws/blob/07b4af13224b32ac298d957a7e949cb33abacbdd/pkg/clients/aws.go#L242
https://github.com/crossplane/provider-aws/blob/07b4af13224b32ac298d957a7e949cb33abacbdd/pkg/clients/aws.go#L351

I think using hostname for session name makes more sense:
>There are different ways to name a role session, and it depends on the method used to assume the IAM role. In some cases, AWS sets the role session on your behalf. For example, for Amazon Elastic Compute Cloud (Amazon EC2) instance profiles, AWS sets the role session name to the instance profile ID. When you use the AssumeRolewithSAML API to assume an IAM role, AWS sets the role session name value to the attribute provided by the identity provider, which your administrator defined. In other cases, you provide the role session name when assuming the IAM role. 
https://aws.amazon.com/blogs/security/easily-control-naming-individual-iam-role-sessions/

Also avoiding creating new sessions too often would be a good idea, because now crossplane creates new sessions very frequently which amounts to a lot of API calls to the STS service.

### How can we reproduce it?
Remove delete access and to try delete an object.

### What environment did it happen in?
provider-aws 0.17

**Comment by muvaf** [comment]
@chlunde I think the frequent re-queuing should be fixed by backoff limiter but I agree unix nano is probably not the best choice for session name. I think using the name of the `Pod` would make sense but it seems that's not available as env var right now. @hasheddan is this something package manager can make available as env var? maybe by using downward api?

**Comment by hasheddan** [comment]
@muvaf yes this can be provided using package manager and `ControllerConfig` today with env var and downward API https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.2.1#spec-env-valueFrom-fieldRef

**Comment by chlunde** [comment]
I think `HOSTNAME` is always set to the container name.

If I understand the SDK correctly, it's not possible to set the session name with the higher level API we use at the moment, but the environment variable `AWS_ROLE_SESSION_NAME` is always checked. So we could do something like this:

```go
const RoleSessionNameEnvKey = "AWS_ROLE_SESSION_NAME"
const DefaultSessionName = "provider-aws"

// in init?
	if os.Getenv(RoleSessionNameEnvKey) == "" {
		os.Setenv(RoleSessionNameEnvKey, DefaultSessionName) // or os.Getenv("HOSTNAME") ?
	}
```

What do you think?

I verified this using:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
...
spec:
  env:
  - name: AWS_ROLE_SESSION_NAME
    value: "provider-aws"
```

But I don't think we should rely on users setting this to avoid "reconcile-storms".
