### ISSUE TITLE
DynamoDB Table to support auto-scaling

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane-contrib/provider-aws#638]
### What problem are you facing?

Currently Table spec (v1alpha1) does not support auto-scaling feature for PROVISIONED resource type

### How could Crossplane help solve your problem?

Add auto-scaling feature

**Comment by jbhennin** [comment]
Another Item to note is that Global Table only works for on-demand because auto-scaling is not available.

**Comment by jbhennin** [comment]
seems there is an ACK for application auto scaling available so this could be something that could be generated.

**Comment by ugurcancaykara** [comment]
Hi, can I get an update about this ?

**Comment by ahmetayd** [comment]
Hi, We need autoscaling for DynamoDB resources. Do you have any solution or workaround?

**Comment by blacksun0504** [comment]
Hello team, any updates on this one?
