### ISSUE TITLE
Secretsmanager: Implement autorotation

### ISSUE THREAD

**Issue by MisterMX** [crossplane-contrib/provider-aws#655]
### What problem are you facing?

As described in #641, Secretsmanager does currently not implement autorotation of secrets in AWS.

### How could Crossplane help solve your problem?

Add an optional `rotation` field to `secret.aws.crossplane.io` that matches the [AWS API](https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#RotateSecretInput).

If this field is set, the provider should enable autoration for the AWS secrets and sync its value back to K8s.

**Comment by janwillies** [comment]
related https://github.com/crossplane/provider-aws/issues/905
