### ISSUE TITLE
IAM user creation fails due to forProvider field

### ISSUE THREAD

**Issue by ranjan68668** [crossplane-contrib/provider-aws#691]
Hi ,

Just to highlight, creation of IAM user fails as it's expecting forProvider as mandatory . I was able to create IAM user by passing tags which doesn't seem to be right. I guess to fix it , we can make forProvider as optional field.

Thanks

**Comment by negz** [comment]
Hi @ranjan68668. Does passing an empty forProvider object work? e.g.

```yaml
spec:
  forProvider: {}
```

**Comment by ranjan68668** [comment]
It does. Just tried.

**Comment by chlunde** [comment]
Should we just add omitEmpty to this type too, @negz ?
```
$ rg ForProvider apis/ | grep json: | grep -i omite
apis/identity/v1alpha1/iamgroup_types.go:	ForProvider       IAMGroupParameters `json:"forProvider,omitempty"`
apis/database/v1beta1/dbsubnetgroup_types.go:	ForProvider       DBSubnetGroupParameters `json:"forProvider,omitempty"`
```
