### ISSUE TITLE
Resource based IAM policy issues - merge code?

### ISSUE THREAD

**Issue by chlunde** [crossplane-contrib/provider-aws#704]
### What happened?
Multiple AWS resources share the structure for a resource based policy. There are many corner cases when comparing resource based policies, such as string order, single vs. multi item lists, map keys, indentation and account ID formats. To avoid infinite reconciles this must be handled. It's not ideal to duplicate this code.

### How can we reproduce it?
See #653 and #700 / #701

### Suggestion / research into refactoring

Should we merge/extract the policy comparision from the ECR controller and reuse for S3?

I tried using the ECR policy struct in S3.. and all the tests still pass. I've not actually tried to deploy it yet.

```
 apis/s3/v1alpha3/bucketpolicy_types.go                                     | 167 +++-----------------------------------------------------------------------------------------------------------------
 apis/s3/v1alpha3/referencers.go                                            |  10 +++----
 apis/s3/v1alpha3/zz_generated.deepcopy.go                                  | 225 ++----------------------------------------------------------------------------------------------------------------------------------------------------------
 pkg/clients/s3/bucketpolicy.go                                             | 143 ---------------------------------------------------------------------------------------------------
 pkg/clients/s3/bucketpolicy_test.go                                        |  37 +++++++++++++-------------
 pkg/controller/s3/bucketpolicy/bucketpolicy.go                             |   3 ++-
 pkg/controller/s3/bucketpolicy/bucketpolicy_test.go                        |  13 ++++-----
```

I think we could wait for #701, and then I can do another PR to extract it to a common structure/package.

@muvaf do you have an idea for a name?

The shared could currently resides in the files mentioned above.

One option would be to move it into an entirely new structure/package, another option would be to create a fake type like "resourcepolicy". Or move it into IAMPolicy (which problably will be able to share a lot of code too).

As this will have to be a stable API i think it *might* make sense to make it v1 internally out of the box, and API change would affect multiple controllers and be hard to track/understand.

##### Option A:
```
 apis/resourcepolicy/v1/types.go
 apis/resourcepolicy/v1/referencers.go  
 apis/resourcepolicy/v1/zz_generated.deepcopy.go
 pkg/clients/resourcepolicy/serialize.go         # Maybe some place else?
 pkg/clients/resourcepolicy/serialize_test.go                        
```

##### Option B: 
... please suggest :)

#### Other changes:
* Some doc strings/URL references would have to be moved to the top level CRD and not the specific fields. Example:
```diff
                             condition:
-                              description: Condition specifies where conditions for policy are in effect. https://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html
+                              description: Condition specifies where conditions for policy are in effect. https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelasticcontainerregistry.html#amazonelasticcontainerregistry-policy-keys
```
* `AllowAnon` and `ID` changes from `bool` -> `*bool` and `string -> *string`. This does not affect the CRD.
* `raw` and `federated` changes order in the CRD. I don't think this matters?

cc @benagricola @krishchow

**Comment by chlunde** [comment]
Here is a list of all services currently supporting resource-based policies: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html

**Comment by chlunde** [comment]
Another issue AWS normalizes `"Action": ["foo"]` to `"Action": "foo"`.
Hack, but I'm sure we can simplify it:
```go
	singleElemArr := cmp.FilterValues(func(x, y interface{}) bool {
		switch v := x.(type) {
		case string:
			yarr, ok := y.([]interface{})
			return ok && len(yarr) == 1
		case []interface{}:
			_, ok := y.(string)
			return ok && len(v) == 1
		}
		return false
	}, cmp.Comparer(func(x, y interface{}) bool {
		switch v := x.(type) {
		case string:
			yarr := y.([]interface{})
			return yarr[0].(string) == v
		case []interface{}:
			s := y.(string)
			return v[0].(string) == s
		}
		return false

	}))
```

**Comment by JasP19** [comment]
Hi all. I just wanted to bump this issue please. We are currently experiencing an issue with our S3 bucket policies. We are constantly seeing PutBucketPolicy events and, as far as I can tell, it must be due to some perceived difference between the policy in our YAML and the policy returned by AWS - we have done some investigation but it is difficult to determine exactly what the difference may be. 

The main issue here is that we are running AWS Config which records an item every time the PutBucketPolicy call is made (every few seconds). This means we are getting thousands of unnecessary items being recorded which has some considerable cost implications as the number of policies managed by Crossplane increases.
