### ISSUE TITLE
Create an example test script

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#705]
### What problem are you facing?

`kubectl apply -f examples` works for most resources but some of the require manual steps, such as domain name registration. That makes it really hard to test whether examples are broken quickly.

### How could Crossplane help solve your problem?

We can have a script that does those manual steps as well as `kubectl apply -f examples` so that we can test all examples quickly. The main use case is to automate CNCF conformance tests https://github.com/cncf/crossplane-conformance/issues/4

**Comment by negz** [comment]
@AaronME mentioned in conversation today that if we had something like this (a script that could spin up all of our example resources) then that plus the provider conformance test suite would serve as a decent integration test suite for the provider.
