### ISSUE TITLE
Service Catalog Product Support

### ISSUE THREAD

**Issue by ryneal** [crossplane-contrib/provider-aws#773]
### What problem are you facing?

The idea is to have a CRD which would define and provision available products in the AWS Service Catalog.

### How could Crossplane help solve your problem?

Automation of service catalog products is limited, to do it in Terraform requires using Terraform to deploy CloudFormation

**Comment by gandhiano** [comment]
Is there any progress here or anyone having similar requirement to provision/deprovision services via the Service Catalog?
