### ISSUE TITLE
ElastiCache: Support LogDeliveryConfigurations field in CacheCluster & ReplicationGroup resources

### ISSUE THREAD

**Issue by tohjustin** [crossplane-contrib/provider-aws#799]
### What problem are you facing?

We would like to configure the `LogDeliveryConfigurations` field in ElastiCache `CacheCluster` & `ReplicationGroup` resources so that we can publish Redis slowlogs to CloudWatch Logs.
 - [Amazon ElastiCache now supports publishing Redis logs to Amazon CloudWatch Logs and Kinesis Data Firehose (April 2021)](https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-elasticache-now-supports-publishing-redis-logs-to-amazon-cloudwatch-logs-and-kinesis-data-firehose/)

### How could Crossplane help solve your problem?

Add a new `.spec.forProvider.logDeliveryConfigurations` field to the `cacheclusters.cache.aws.crossplane.io` & `replicationgroups.cache.aws.crossplane.io` CRDs.

#### ~~Blockers~~

- ~~`LogDeliveryConfigurations` field is added in [aws/aws-sdk-go-v2@v1.3.4](https://github.com/aws/aws-sdk-go-v2/blob/v1.3.4/service/elasticache/types/types.go#L156) but the lastest version of [crossplane/provider-aws@v0.19.0](https://github.com/crossplane/provider-aws/releases/tag/v0.19.0) still using [aws/aws-sdk-go-v2@v0.23.0](https://github.com/crossplane/provider-aws/blob/v0.19.0/go.mod#L7)~~
- ~~Will have to wait for https://github.com/crossplane/provider-aws/pull/602 to merge & upgrade [aws/aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) to v1.3.4+~~

**Comment by haarchri** [comment]
@tohjustin #602 is merged
