### ISSUE TITLE
Document Provider Flags

### ISSUE THREAD

**Issue by luebken** [crossplane-contrib/provider-aws#808]
### What problem are you facing?

I'm trying to explore the behavior of this provider. This could be pure exploratory or in some troubleshooting use-case. 

### How could Crossplane help solve your problem?

https://github.com/crossplane/provider-aws/blob/master/cmd/provider/main.go#L36 lists a couple of flags that are useful: debug, sync, poll, leader-election. These should be documented and how us user can set them. e.g. with [ControllerConfig](https://crossplane.io/docs/v1.3/reference/troubleshoot.html#provider-logs)

**Comment by haarchri** [comment]
@luebken  think this would be a good task for generic crossplane documentation ?
i will close this issue
