### ISSUE TITLE
RDS Read Replica (not Aurora) 

### ISSUE THREAD

**Issue by OmerKahani** [crossplane-contrib/provider-aws#820]
### What problem are you facing?
There isn't a support for creating a read replica for an RDS instance that is not Aurora.

### How could Crossplane help solve your problem?
The Terraform provider, which is based on the same SDK, has this option by calling the `CreateDBInstanceReadReplica` function.
TF code: https://github.com/hashicorp/terraform-provider-aws/blob/1e34195292789afd8871cb47aa7861f033f31e32/aws/resource_aws_db_instance.go#L663
The function in the SDK: https://github.com/aws/aws-sdk-go/blob/0522fa00e4a73b5853ec3051b882880dbffab385/models/apis/rds/2014-10-31/api-2.json#L369

### Suggested Solution 
I can think of two ways to add a call to this function:
1. Same as the implementation of the TF provider, adding a parameter in the managed resource (`DBInstance`) we have today and an if statement in the code
2. Create a new managed resource `DBInstanceReadReplica`, which would expose only the parameters that `CreateDBInstanceReadReplica` accepted
In this option, we expose a more explicit API, but it creates a new managed resource

**Comment by agill17** [comment]
Has there been a decision made on this? The latter does sound ( explicit API / controller / resource ) for creating a Read Replica for non-aurora DBInstances. I would not mind taking a stab at this if there has been a decision made

**Comment by avdhoot** [comment]
@muvaf @haarchri @chlunde  Any progress or suggestion on how this can be done?

**Comment by chlunde** [comment]
I worry that there would be significant overlap in the reconcile loop for another resource. Have anyone checked what the parameter overlap is, what options are new for replicas, and what options are not available in replicas. If there's only one extra parameter for replicas and all other parameters are valid, it would sound like the API could be implemented similar to how restores work.

How should the workflow for promoting an instance be? If it's a different type this would be difficult.

**Comment by mateusz-lubanski-sinch** [comment]
also looking forward for this functionality
