### ISSUE TITLE
Inconsistent tagging syntax 

### ISSUE THREAD

**Issue by masturd** [crossplane-contrib/provider-aws#827]
### What happened?

i dont know if this is a bug or intended but the tagging syntax are not consistent between controllers:
ec2 is using a list https://github.com/crossplane/provider-aws/blob/e755b74d03877f2aa9a3b8783c3f579316441a87/pkg/controller/ec2/vpc/controller_test.go#L65
eks is using a map https://github.com/crossplane/provider-aws/blob/e755b74d03877f2aa9a3b8783c3f579316441a87/pkg/controller/eks/cluster_test.go#L64

### How can we reproduce it?

ec2 tagging:
```
- tags:
   - key: test
    value: true
```
while eks will fail 

### What environment did it happen in?
Crossplane version: v1.4

**Comment by RedbackThomson** [comment]
We are aware of this issue in the ACK project. This boils down to the fact that each service handles tag semantics differently in their `Create*` requests. Some require KV pairs, others require slices of KV structs. It's in the roadmap to tackle this at a global level, and abstract the difference away behind the scenes. See https://github.com/aws-controllers-k8s/community/issues/63 for that roadmap item.
