### ISSUE TITLE
DynamoDB resource not sync Tags when is updated

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane-contrib/provider-aws#945]
### What happened?
Expecting DynamoDB to have sync Up Tags when it differs from the managed resource manifest

### How can we reproduce it?

Update or remove Tags from the UI don't reflect the changes in the managed resource manifest 

Tie back the managed resource manifest (e.g. Table) with Tags fields , to a resource that already exist in Cloud Provider without Tags field.
Expecting the Tags will be sync up eventually based on manifest

I am suspecting the isUpToDate function does not include Tags check: https://github.com/crossplane/provider-aws/blob/a6b684da013d65cd2a25288327eb3ea5a03b6c0e/pkg/controller/dynamodb/table/hooks.go#L292
 
I think similar issue with globaltable and backup

### What environment did it happen in?
Crossplane version: provider-aws:v0.18.0

**Comment by negz** [comment]
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTable.html
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TagResource.html

It seems like the `UpdateTable` call we're making doesn't support updating tags, even though `CreateTable` does. My guess is that supporting tag updates might be tricky, given we'd need to:

1. Call `TagResource` somewhere - maybe the `postUpdate` hook.
2. Somehow have the code generator _only_ call `TagResource` (and not `UpdateTable`) if only the tags changed.

Not sure if it's possible to do this today given this resource is ACK generated.
