### ISSUE TITLE
Implement Workspaces for AWS Managed Service for Prometheus (AMP)

### ISSUE THREAD

**Issue by janwillies** [crossplane-contrib/provider-aws#977]
### What resource do you need?

[AWS Managed Service for Prometheus](https://docs.aws.amazon.com/prometheus/latest/userguide/what-is-Amazon-Managed-Service-Prometheus.html) (AMP) is a managed prometheus offering

CRUD operations for [Workspaces](https://github.com/aws/aws-sdk-go/blob/7765b5509c719ac9c6a744097fe499e780a9aed7/service/prometheusservice/api.go#L252) are missing in `provider-aws`

### What is your use case?

Storing metrics from Kubernetes workloads in a managed database

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
yes, however the [current version](https://github.com/crossplane/provider-aws/blob/master/go.mod#L6) of the `aws-sdk-go` in crossplane doesn't implement `Tags`: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.37.4/service/prometheusservice#CreateWorkspaceInput. 

A newer version of the `aws-sdk-go` is necessary to suppport tags: https://github.com/crossplane/provider-aws/pull/918

**Comment by haarchri** [comment]
implemented with #1054
