### ISSUE TITLE
DynamoDB Unable to Create Replicas using version 2019.11.21 

### ISSUE THREAD

**Issue by jbhennin** [crossplane-contrib/provider-aws#979]
### What happened?

The Global Table implementation is only for the non-current version of dynamodb Global Tables.  See (https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#DynamoDB.CreateGlobalTable)

We should be creating the replicas using the current version of Global Table.  Reference:  https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables.tutorial.html#V2creategt_java

### How can we reproduce it?
Create a Table and then create a Global Table with the desired regions in which replicas should be created.   An error will be returned stating the table does not exist.   The way Global Table works for 2019 version is that the replicas will be created if you have global secondary indexes set and you pass in regions within the replicationGroup object

### What environment did it happen in?
provider-aws: v0.21.2

**Comment by ppeble** [comment]
Throwing in my two cents that we would love for this to be prioritized, we have a use case for it but cannot use the old version so we're stuck not using Crossplane for it.

**Comment by saatvik-chugh** [comment]
any updates for this?
