### ISSUE TITLE
DynamoDB Unable to Update the billingMode

### ISSUE THREAD

**Issue by jbhennin** [crossplane-contrib/provider-aws#982]
### What happened?
Updating a Table from  PROVISIONED to PAY_PER_REQUEST fails and the following error is returned:
`update failed: pre-update failed: only provisionedThroughput and streamSpecification updates are supported`

Billing Mode is not immutable and should be able to be changed. 

### How can we reproduce it?
Create Table with billingMode PROVISIONED, then change to PAY_PER_REQUEST.
Be sure to remove the provisionedThroughput input parameters

### What environment did it happen in?
aws provider: v0.21.2

**Comment by chlunde** [comment]
I believe this was fixed with #839 - please reopen if it's still an issue. That specific error message was deleted in that commit. Thanks!
