### ISSUE TITLE
Rename of Cache/ElastiCache resources

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-aws#991]
### What problem are you facing?

we have `CacheCluster`, `CacheSubnetGroup`, `ReplicationGroup` in `cache.aws.crossplane.io` group. However, If we merge the PR https://github.com/crossplane/provider-aws/pull/585 we have Code-Generator resources generated in `elasticache.aws.crossplane.io`

### How could Crossplane help solve your problem?

we need to be consistent under `elasticache.aws.crossplane.io` for all resources we have

**Comment by muvaf** [comment]
I think this makes sense; similar to how we're moving `RDSInstance` in `database` to `DBInstance` in `rds`.

**Comment by haarchri** [comment]
think we can do this in #1011
